<?php
echo $this->UIPageTitleFormatter($this->navigation('navigation')->findActive('navigation')['page']->label);

$form->setAttribute('action', $this->url('business-admin/suppliers', array('action' => 'add')));
$form->setAttributes(array('class' => 'form-horizontal'));
$form->prepare();
?>

<div class="well bs-component">

    <?php echo $this->form()->openTag($form); ?>

    <fieldset>
        <legend>Add Supplier</legend>

        <?php echo $this->formHidden($form->get('RMSupplierID')); ?>

        <div class="form-group">
            <label class="col-lg-2 control-label" for="RMSupplierName">Supplier Name:</label>
            <div class="col-lg-10">
                <?php echo $this->formRow($form->get('RMSupplierName')); ?>
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-3 col-lg-offset-9">
                <a href="/business-admin/suppliers" type="reset" class="btn btn-default">Cancel</a>
                <?php echo $this->formSubmit($form->get('submit')); ?>
            </div>
        </div>

    </fieldset>

    <?php echo $this->form()->closeTag(); ?>

</div>
