<div class="page-header">
    <h1>Admin Users</h1>
</div>

<?php
$form->setAttribute('action', $this->url('admin-users', array('action' => 'add')));
$form->setAttributes(array('class' => 'form-horizontal'));
$form->prepare();

echo '<div class="col-lg-10"><div class="well bs-component">';

echo $this->form()->openTag($form);

echo '<fieldset><legend>Add New User</legend>';

echo $this->formHidden($form->get('id'));

echo '<div class="form-group">';
echo '<label class="col-lg-2 control-label" for="firstname">Firstname:</label><div class="col-lg-10">';
echo $this->formRow($form->get('firstname'));
echo '</div></div>';

echo '<div class="form-group">';
echo '<label class="col-lg-2 control-label" for="lastname">Lastname:</label><div class="col-lg-10">';
echo $this->formRow($form->get('lastname'));
echo '</div></div>';

echo '<div class="form-group">';
echo '<label class="col-lg-2 control-label" for="username">Username:</label><div class="col-lg-10">';
echo $this->formRow($form->get('username'));
echo '</div></div>';

echo '<div id="pwd-container"><div class="form-group">';
echo '<label class="col-lg-2 control-label" for="password">Password:</label><div class="col-lg-10">';
echo $this->formRow($form->get('password'));
echo '</div></div>';
echo '<div class="col-sm-6 col-sm-offset-2">';
echo '<div class="pwstrength_viewport_progress"></div></div></div>';

echo '<div class="form-group">';
echo '<div class="col-lg-10 col-lg-offset-2">';
echo '<a href="/admin-users" type="reset" class="btn btn-default">Cancel</a>';
$form->get('submit')->setAttribute('class', 'btn btn-success');
echo $this->formSubmit($form->get('submit'));
echo '</div></div>';

echo '</fieldset>';

echo $this->form()->closeTag();

echo '</div></div>';

echo $this->inlineScript()->appendFile('/js/pwstrength-bootstrap.min.js');
?>

<script>
    jQuery(document).ready(function () {
        "use strict";
        var options = {};
        options.ui = {
            container: "#pwd-container",
            verdicts: [
                "<span class='fa fa-exclamation-triangle'></span> Weak",
                "<span class='fa fa-exclamation-triangle'></span> Normal",
                "Medium",
                "<span class='fa fa-thumbs-up'></span> Strong",
                "<span class='fa fa-thumbs-up'></span> Very Strong"],
            showVerdictsInsideProgressBar: true,
            viewports: {
                progress: ".pwstrength_viewport_progress"
            }
        };
        options.common = {
            debug: true,
            onLoad: function () {
                $('#messages').text('Start typing password');
            }
        };
        $(':password').pwstrength(options);
    });
    window.onload = function () {
        setTimeout(function () {
            document.getElementById('username').value = '';
            document.getElementById('password').value = '';
        }, 10);
    }
</script>