<?php
echo $this->UIPageTitleFormatter('<span class="glyphicon glyphicon-trash"></span> Delete this User?');
$url = $this->url(NULL, array('action' => 'delete', 'id' => $this->id,));
?>

<div class="well bs-component">
    <form action="<?php echo $url; ?>" method="post">

        <fieldset>

            <div class="form-group">
                <div class="col-lg-10">
                    <div class="panel panel-warning">
                        <div class="panel-heading">
                            <h3 class="panel-title">Warning!</h3>
                        </div>
                        <div class="panel-body">
                            Are you sure that you want to delete <span class="text-warning bold">"<?php echo $this->escapeHtml($users->firstname . ' ' . $users->lastname); ?>"</span>?
                        </div>
                    </div>
                </div>
            </div>

            <input type="hidden" name="id" value="<?php echo (int) $users->id; ?>" />
            <div class="form-group">
                <div class="col-lg-3 col-lg-offset-7">
                    <button type="submit" class="btn btn-default btn-sm margin-right-10" name="del" value="No">Cancel</button>
                    <button type="submit" class="btn btn-danger btn-sm" name="del" value="Yes">Delete</button>
                </div>
            </div>
        </fieldset>

    </form>

</div>