<?php
echo $this->UIPageTitleFormatter($this->navigation('navigation')->findActive('navigation')['page']->label);

$form = $this->form;
$form->setAttribute('action', $this->url('user-admin', array('action' => 'edit', 'id' => $this->id,)));
$form->setAttributes(array('class' => 'form-horizontal'));

$form->prepare();
?>

<div class="well bs-component">

    <?php echo $this->form()->openTag($form); ?>

    <fieldset>
        <legend>Edit New User</legend>

        <?php echo $this->formHidden($form->get('id')); ?>

        <div class="form-group">
            <label class="col-lg-2 control-label" for="firstname">Firstname:</label><div class="col-lg-10">
                <?php echo $this->formRow($form->get('firstname')); ?>
            </div></div>

        <div class="form-group">
            <label class="col-lg-2 control-label" for="lastname">Lastname:</label><div class="col-lg-10">
                <?php echo $this->formRow($form->get('lastname')); ?>
            </div></div>

        <div class="form-group">
            <label class="col-lg-2 control-label" for="username">Username:</label><div class="col-lg-10">
                <div class="input-group"><span class="input-group-addon">@</span>
                    <?php echo $this->formRow($form->get('username')); ?>
                </div></div></div>

        <div class="form-group">
            <label class="col-lg-2 control-label" for="role_level">Role Level:</label><div class="col-lg-10">
                <?php echo $this->formRow($form->get('role_level')); ?>
            </div></div>

        <div id="pwd-container"><div class="form-group">
                <label class="col-lg-2 control-label" for="password">Password:</label><div class="col-lg-10">
                    <?php echo $this->formRow($form->get('password')); ?>
                </div></div>
            <div class="col-sm-6 col-sm-offset-2">
                <div class="pwstrength_viewport_progress"></div></div></div>

        <div class="form-group">
            <div class="col-lg-10 col-lg-offset-2">
                <a href="/user-admin" type="reset" class="btn btn-default margin-right-10">Cancel</a>
                <?php echo $this->formSubmit($form->get('submit')); ?>
            </div></div>

    </fieldset>

    <?php echo $this->form()->closeTag(); ?>

</div>

<?php echo $this->inlineScript()->appendFile('/js/pwstrength-bootstrap.min.js'); ?>

<script>
    jQuery(document).ready(function () {
        "use strict";
        var options = {
        };
        options.ui = {
            container: "#pwd-container",
            verdicts: [
                "<span class='fa fa-exclamation-triangle'></span> Weak",
                "<span class='fa fa-exclamation-triangle'></span> Normal",
                "Medium",
                "<span class='fa fa-thumbs-up'></span> Strong",
                "<span class='fa fa-thumbs-up'></span> Very Strong"],
            showVerdictsInsideProgressBar: true,
            viewports: {
                progress: ".pwstrength_viewport_progress"
            }
        };
        options.common = {
            debug: true,
            onLoad: function () {
                $('#messages').text('Start typing password');
            }
        };
        $(':password').pwstrength(options);
    });
</script>
