<div class="page-header">
    <h1>Admin Users</h1>
</div>

<div class="col-lg-8">

    <?php echo $this->UIAccessControlButtons($_SESSION['AnnieHaak']['storage']['userInfo']['roleLevel'], 'add', '/user-admin/add', 'Add new user'); ?>

    <table class="table table-striped table-hover ">
        <thead>
            <tr>
                <th>Full Name</th>
                <th colspan="2">Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($users as $user) : ?>
                <tr>
                    <td>
                        <h4>
                            <?php
                            echo $this->escapeHtml($user->firstname . ' ' . $user->firstname);
                            ?>
                        </h4>
                    </td>
                    <td>
                        <?php echo $this->UIAccessControlButtons($_SESSION['AnnieHaak']['storage']['userInfo']['roleLevel'], 'edit', '/user-admin/edit/' . $user->id, 'Edit'); ?>
                    </td>
                    <td>
                        <?php echo $this->UIAccessControlButtons($_SESSION['AnnieHaak']['storage']['userInfo']['roleLevel'], 'delete', '/user-admin/delete/' . $user->id, 'Delete'); ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

</div>