<?php
dump($this->navigation('navigation'));
dump($this->navigation('navigation')->findActive('navigation')['page']);
echo $this->UIPageTitleFormatter($this->navigation('navigation')->findActive('navigation')['page']->label);
echo $this->UIAccessControlButtons($_SESSION['AnnieHaak']['storage']['userInfo']['roleLevel'], 'add', '/user-admin/add', 'Add new user');
?>

<table class="table table-striped table-hover ">
    <thead>
        <tr class="text-info">
            <th>Full Name</th>
            <th colspan="2" style="width: 25%;">Actions</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($users as $user) : ?>
            <tr>
                <td>
                    <?php echo $this->escapeHtml($user->firstname . ' ' . $user->lastname); ?>
                </td>
                <td>
                    <?php echo $this->UIAccessControlButtons($_SESSION['AnnieHaak']['storage']['userInfo']['roleLevel'], 'edit', '/user-admin/edit/' . $user->id, 'Edit'); ?>
                </td>
                <td>
                    <?php
                    if (count($users) > 1) {
                        echo $this->UIAccessControlButtons($_SESSION['AnnieHaak']['storage']['userInfo']['roleLevel'], 'delete', '/user-admin/delete/' . $user->id, 'Delete');
                    } else {
                        echo '&nbsp;';
                    }
                    ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>