<?php
echo $this->UIPageTitleFormatter($this->navigation('navigation')->findActive('navigation')['page']->label);

$form->setAttribute('action', $this->url('business-admin/products', array('action' => 'add')));
$form->setAttributes(array('class' => 'form-horizontal'));
$form->prepare();
?>

<div class="well bs-component">

    <?php echo$this->form()->openTag($form) ?>

    <fieldset>
        <legend>Add New Product</legend>
        <div id="NewProductBlock" class="in ">

            <?php echo $this->formHidden($form->get('ProductID')->setValue(0)) ?>

            <div class="form-group">
                <label class="col-lg-2 control-label" for="ProductName">Product Name:</label>
                <div class="col-lg-10">
                    <?php echo $this->formRow($form->get('ProductName')); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-2 control-label" for="SKU">SKU:</label>
                <div class="col-lg-10">
                    <?php echo $this->formRow($form->get('SKU')); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-2 control-label" for="CollectionID">Collection:</label>
                <div class="col-lg-10">
                    <?php echo $this->formRow($form->get('CollectionID')); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-2 control-label" for="ProductTypeID">Product Type:</label>
                <div class="col-lg-10">
                    <?php echo $this->formRow($form->get('ProductTypeID')); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-2 control-label" for="Strands">Strands:</label>
                <div class="col-lg-10">
                    <?php echo $this->formRow($form->get('Strands')); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-2 control-label" for="IntroDate">Date Introduced:</label>
                <div class="col-lg-10">
                    <?php echo $this->formRow($form->get('IntroDate')->setValue(date('Y-m-d'))); ?>
                </div>
            </div>

        </div>

    </fieldset>

    <fieldset>
        <legend>Raw Materials</legend>
        <?php #echo $this->UIProductRawMaterialsManager(TRUE, $this->rawMaterials)['rmReturnBlock']; ?>

        <div class="row">
            <div class="col-lg-10 col-lg-offset-2">
                <table id="rawMaterialGrid"></table>
                <div id="rawMaterialGridPager"></div>
            </div>
        </div>
        <script type="text/javascript">
            $(document).ready(function () {
                var rawMaterialsCurrentData = [];
                var rawMaterialTypesData = function () {
                    var rtnData = null;
                    $.ajax({
                        async: false,
                        url: "/business-admin/raw-material-types/jsonAllMaterialTypes",
                        success: function (data, result) {
                            rtnData = '0:Select ...;';
                            if (!result) {
                                alert('ERROR');
                            } else {
                                for (var x = 0; x < data.rawMaterialTypes.length; x++) {
                                    rtnData += data.rawMaterialTypes[x]['id'] + ':' + data.rawMaterialTypes[x]['value'];
                                    if (data.rawMaterialTypes.length - 1 > x) {
                                        rtnData += ';';
                                    }
                                }
                            }
                        }
                    });
                    return rtnData;
                }();
                var rawMaterialsData = function () {
                    var rtnData = null;
                    $.ajax({
                        async: false,
                        url: "/business-admin/raw-materials/jsonAllMaterials",
                        success: function (data, result) {
                            rtnData = '0:Select ...;';
                            if (!result) {
                                alert('ERROR');
                            } else {
                                for (var x = 0; x < data.rawMaterials.length; x++) {
                                    rtnData += data.rawMaterials[x]['id'] + ':' + data.rawMaterials[x]['value'];
                                    if (data.rawMaterials.length - 1 > x) {
                                        rtnData += ';'
                                    }
                                }
                            }
                        }
                    });
                    return rtnData;
                }();
                onclickSubmitLocal = function (options, postdata) {
                    console.log(postdata);
                    this.processing = true;
                    return {};
                }

                $.jgrid.defaults.responsive = true;
                $.jgrid.defaults.styleUI = 'Bootstrap';
                $("#rawMaterialGrid").jqGrid({
                    url: '/business-admin/raw-materials/jsonMaterialsByProduct?productid=1855',
                    mtype: "GET",
                    datatype: "json",
                    styleUI: 'Bootstrap',
                    viewrecords: true,
                    loadonce: false,
                    sortname: '',
                    height: 'auto',
                    viewsortcols: [false, 'vertical', false],
                    pager: "#rawMaterialGridPager",
                    editurl: 'clientArray',
                    loadComplete: function () {
                    },
                    colNames: ['Raw Material Type', 'Raw Material Name', 'Code', 'Supplier', 'Quantity', 'Cost', 'Subtotal'],
                    colModel: [
                        {
                            name: 'RMTypeID',
                            width: 200,
                            editable: true,
                            edittype: 'select',
                            formatter: 'select',
                            editoptions: {
                                value: rawMaterialTypesData
                            }
                        },
                        {
                            name: 'RawMaterialID',
                            width: 200,
                            editable: true,
                            edittype: "select",
                            formatter: 'select',
                            editoptions: {
                                value: rawMaterialsData
                            },
                            editrules: {
                                required: true,
                                number: true
                            }
                        },
                        {
                            name: 'RawMaterialCode',
                            width: 75,
                            edittype: "text",
                            editable: true,
                            editoptions: {
                                readonly: true
                            }
                        },
                        {
                            name: 'RMSupplierName',
                            width: 150,
                            edittype: "text",
                            editable: true,
                            editoptions: {
                                readonly: true
                            }
                        },
                        {
                            name: 'RawMaterialQty',
                            width: 75,
                            edittype: "text",
                            editable: true
                        },
                        {
                            name: 'RawMaterialUnitCost',
                            width: 75,
                            edittype: "text",
                            editable: true,
                            editoptions: {
                                readonly: true
                            }
                        },
                        {
                            name: 'Subtotal',
                            width: 75,
                            edittype: "text",
                            editable: true,
                            editoptions: {
                                readonly: true,
                                size: 15,
                                maxlengh: 10,
                            }
                        }
                    ]
                });
                $('#rawMaterialGrid').navGrid('#rawMaterialGridPager', {
                    edit: true,
                    add: true,
                    del: true,
                    search: false,
                    refresh: false,
                    view: false,
                    position: "left",
                    cloneToTop: true
                },
                {
                    // EDIT
                    editCaption: "Edit this Raw Material",
                    recreateForm: false,
                    closeAfterEdit: true,
                    viewPagerButtons: false,
                    afterShowForm: RawMaterialData,
                    errorTextFormat: function (data) {
                        return 'Error: ' + data.responseText
                    },
                    reloadAfterSubmit: true,
                    closeOnEscape: true,
                    savekey: [true, 13],
                    onclickSubmit: onclickSubmitLocal
                },
                {
                    // ADD
                    closeAfterAdd: true,
                    recreateForm: false,
                    errorTextFormat: function (data) {
                        return 'Error: ' + data.responseText
                    }
                },
                {
                    // DELETE
                    errorTextFormat: function (data) {
                        return 'Error: ' + data.responseText
                    }
                });

                function RawMaterialData() {
                    $("#RawMaterialQty").unbind('keyup change');
                    $('#RawMaterialQty').numericInput(false, false);
                    $('#RawMaterialQty').on('keyup change', function () {
                        $('#Subtotal').val(parseFloat((parseFloat($("#RawMaterialUnitCost").val()) * parseInt($("#RawMaterialQty").val())).toFixed(4)));
                    });
                    updateRawMaterialCallBack($("#RMTypeID").val(), true);
                    $("#RMTypeID").bind("change", function (e) {
                        updateRawMaterialCallBack($("#RMTypeID").val(), false);
                        $('#RawMaterialCode').val('');
                        $('#RMSupplierName').val('');
                        $('#RawMaterialQty').val(1);
                        $('#RawMaterialUnitCost').val(0);
                        $('#RawMaterialQty').val(0);
                        $('#Subtotal').val(0);
                    });
                    return false;
                }

                function updateRawMaterialCallBack(RawMaterialTypeId, setselected) {
                    var current = $("#rawMaterialGrid").jqGrid('getRowData', $("#rawMaterialGrid")[0].p.selrow).RawMaterialID;
                    $("#RawMaterialID")
                            .html('<option value="">Loading Raw Materials...</option>')
                            .attr("disabled", "disabled");
                    $.ajax({
                        url: "/business-admin/raw-materials/jsonMaterialsByType?RawMaterialTypeId=" + RawMaterialTypeId,
                        type: "GET",
                        success: function (data) {
                            rawMaterialsCurrentData = data.rawMaterials;

                            var selectHtml = '<select><option value="0">Select ...</option>';
                            for (var x = 0; x < data.rawMaterials.length; x++) {
                                selectHtml += '<option value="' + data.rawMaterials[x]['RawMaterialID'] + '">' + data.rawMaterials[x]['RawMaterialName'] + '</option>';
                            }
                            selectHtml += '</select>';
                            $("#RawMaterialID")
                                    .removeAttr("disabled")
                                    .html(selectHtml);
                            if (setselected) {
                                $("#RawMaterialID").val(current);
                            }
                            $("#RawMaterialID").bind("change", function (e) {
                                rmObject = null;
                                for (var i = 0, len = rawMaterialsCurrentData.length; i < len; i++) {
                                    if (rawMaterialsCurrentData[i].RawMaterialID === e.currentTarget.value)
                                        rmObject = rawMaterialsCurrentData[i];
                                }
                                $('#RawMaterialQty').val(1);
                                $('#RawMaterialUnitCost').val(0);
                                $('#RawMaterialCode').val(rmObject.RawMaterialCode);
                                $('#RMSupplierName').val(rmObject.RMSupplierName);
                                $('#RawMaterialUnitCost').val(rmObject.RawMaterialUnitCost);
                                $('#Subtotal').val(parseFloat((parseFloat($("#RawMaterialUnitCost").val()) * parseInt($("#RawMaterialQty").val())).toFixed(4)));
                            });
                        }
                    });
                }

            });
        </script>
        <script type="application/javascript" src="/js/jqGrid/bootstrap/integrations/amdsupport/js/i18n/grid.locale-en.js?v=1"></script>
        <script type="application/javascript" src="/js/jqGrid/js/trirand/jquery.jqGrid.min.js"></script>


    </fieldset>

    <!-- /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// --->

    <fieldset>
        <legend>Labour</legend>
    </fieldset>

    <!-- /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// --->

    <fieldset>
        <legend>Dispatch</legend>

    </fieldset>

    <!-- /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// --->

    <fieldset>
        <legend>Packaging</legend>

    </fieldset>

    <!-- /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// --->

    <fieldset>
        <legend>Financial</legend>

    </fieldset>

    <div class="form-group">
        <div class="col-lg-3 col-lg-offset-9">
            <a href="/business-admin/raw-material-types" type="reset" class="btn btn-default">Cancel</a>
            <?php echo $this->formSubmit($form->get('submit')); ?>
        </div>
    </div>

    <!-- /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// --->

    <div class="modal fade" id="buildProductName" tabindex="-1" role="dialog" aria-labelledby="buildProductNameLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="buildProductNameLabel">Build Product Name</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label class="col-lg-3 control-label" for="Name">Name:</label>
                        <div class="col-lg-9">
                            <?php echo $this->formRow($form->get('Name')); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-3 control-label" for="NameCharm">Choose Charm:</label>
                        <div class="col-lg-9">
                            <?php echo $this->formRow($form->get('NameCharm')); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-3 control-label" for="NameCrystal">Choose Crystal:</label>
                        <div class="col-lg-9">
                            <?php echo $this->formRow($form->get('NameCrystal')); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-3 control-label" for="NameColour">Choose Colour:</label>
                        <div class="col-lg-9">
                            <?php echo $this->formRow($form->get('NameColour')); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-3 control-label" for="NameLength">Choose Length:</label>
                        <div class="col-lg-9">
                            <?php echo $this->formRow($form->get('NameLength')); ?>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" id="buildProductNameSave" class="btn btn-success" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <!-- /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// --->

    <div class="modal fade" id="manageRawMaterials" tabindex="-1" role="dialog" aria-labelledby="manageRawMaterialsLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="manageRawMaterialsLabel">Add Raw Material</h4>
                </div>
                <div class="modal-body">
                    <select name="testSelect" id="testSelect">
                        <option value="1">testSelect - 1</option>
                        <option value="2">testSelect - 2</option>
                        <option value="3">testSelect - 3</option>
                        <option value="4">testSelect - 4</option>
                        <option value="5">testSelect - 5</option>
                    </select>
                </div>
                <div class="modal-footer">
                    <button type="button" id="addRawMaterialSave" class="btn btn-success" data-dismiss="modal">Add</button>
                </div>
            </div>
        </div>
    </div>

    <!-- /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// --->

    <?php echo $this->form()->closeTag(); ?>

</div>

<script>
            $(document).ready(function () {
                $('#ProductName').focus(function () {
                    $('#buildProductName').modal('show');
                    $('#Name').focus();
                });
                $('#buildProductName').on('hidden.bs.modal', function () {
                    $('#SKU').focus();
                });
                //=============================================
                $("#IntroDate").datepicker({
                    autoclose: true,
                    dateFormat: "yy-mm-dd",
                    format: 'dd-mm-yy',
                    altFormat: "yy-mm-dd",
                    orientation: 'bottom',
                    changeMonth: true,
                    changeYear: true
                });
                //=============================================
                $("#Name").bind('keyup', function () {
                    concatName();
                });
                $("#Charm").bind('change', function () {
                    concatName();
                });
                $("#Chrystal").bind('change', function () {
                    concatName();
                });
                $("#Colour").bind('change', function () {
                    concatName();
                });
                $("#Length").bind('change', function () {
                    concatName();
                });
                $("#buildProductNameSave").click(function () {
                    concatName();
                });
                concatName = function () {
                    $("#ProductName").val($("#Name").val());
                    if ($("#NameCharm").val()) {
                        $("#ProductName").val($("#ProductName").val() + ' - ' + $("#NameCharm").val());
                    }
                    if ($("#NameCrystal").val()) {
                        $("#ProductName").val($("#ProductName").val() + ' - ' + $("#NameCrystal").val());
                    }
                    if ($("#NameColour").val()) {
                        $("#ProductName").val($("#ProductName").val() + ' - ' + $("#NameColour").val());
                    }
                    if ($("#NameLength").val()) {
                        $("#ProductName").val($("#ProductName").val() + ' - ' + $("#NameLength").val());
                    }
                };
            });
</script>
