<?php
echo $this->UIPageTitleFormatter($this->navigation('navigation')->findActive('navigation')['page']->label);
$productId = 2570;
$form->setAttribute('action', $this->url('business-admin/products', array('action' => 'add')));
$form->setAttributes(array('class' => 'form-horizontal'));
$form->prepare();

echo $this->form()->openTag($form)
?>

<div class="well bs-component">

    <fieldset>

        <legend>Add New Product</legend>

        <?php echo $this->formHidden($form->get('ProductID')) ?>

        <div class="form-group">
            <label class="col-lg-2 control-label" for="ProductName">Product Name:</label>
            <div class="col-lg-10">
                <?php echo $this->formRow($form->get('ProductName')); ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-lg-2 control-label" for="SKU">SKU:</label>
            <div class="col-lg-10">
                <?php echo $this->formRow($form->get('SKU')); ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-lg-2 control-label" for="CollectionID">Collection:</label>
            <div class="col-lg-10">
                <?php echo $this->formRow($form->get('CollectionID')); ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-lg-2 control-label" for="ProductTypeID">Product Type:</label>
            <div class="col-lg-10">
                <?php echo $this->formRow($form->get('ProductTypeID')); ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-lg-2 control-label" for="Strands">Strands:</label>
            <div class="col-lg-10">
                <?php echo $this->formRow($form->get('Strands')); ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-lg-2 control-label" for="IntroDate">Date Introduced:</label>
            <div class="col-lg-10">
                <?php echo $this->formRow($form->get('IntroDate')->setValue(date('Y-m-d'))); ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-lg-2 control-label" for="MinsToBuild">Mins To Build:</label>
            <div class="col-lg-10">
                <?php echo $this->formRow($form->get('MinsToBuild')->setValue(1)); ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-lg-2 control-label" for="QtyOrderedLastPeriod">Sold Last Period:</label>
            <div class="col-lg-10">
                <?php echo $this->formRow($form->get('QtyOrderedLastPeriod')->setValue(0)); ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-lg-2 control-label" for="CurrentURL">Current URL:</label>
            <div class="col-lg-10">
                <?php echo $this->formRow($form->get('CurrentURL')); ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-lg-2 control-label" for="OldURL">Old URL:</label>
            <div class="col-lg-10">
                <?php echo $this->formRow($form->get('OldURL')); ?>
            </div>
        </div>

        <div class="form-group" id="DescBlock">
            <label class="col-lg-2 control-label" for="Description">Description:</label>
            <div class="col-lg-10">
                <div class="row">
                    <div class="col-lg-10">
                        <?php echo $this->formRow($form->get('Description')); ?>
                    </div>
                    <div class="col-lg-2">
                        <div class="radio radio-danger">
                            <input name="DescriptionStatus" id="DescRadio1" value="0" type="radio" checked="checked" />
                            <label for="DescRadio1">
                                <span class="label label-danger">Needs Description</span>
                            </label>
                        </div>
                        <div class="radio radio-warning">
                            <input name="DescriptionStatus" id="DescRadio2" value="1" type="radio" />
                            <label for="DescRadio2">
                                <span class="label label-default">Pending Approval</span>
                            </label>
                        </div>
                        <div class="radio radio-success">
                            <input name="DescriptionStatus" id="DescRadio3" value="2" type="radio" />
                            <label for="DescRadio3">
                                <span class="label label-default">Approved</span>
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">

            <label class="col-lg-2 control-label" for="Description">Options:</label>

            <div class="col-lg-10">

                <div class="row" id="optionsBlock">

                    <div class="col-lg-2">
                        <div class="checkbox checkbox-success">
                            <?php echo $this->formRow($form->get('KeyPiece')); ?>
                            <label for="KeyPiece">
                                <span class="label label-default">Key Piece</span>
                            </label>
                        </div>
                        <div class="checkbox checkbox-success">
                            <?php echo $this->formRow($form->get('Accessories')); ?>
                            <label for="Accessories">
                                <span class="label label-default">Accessories</span>
                            </label>
                        </div>
                        <div class="checkbox checkbox-success">
                            <?php echo $this->formRow($form->get('Friendship')); ?>
                            <label for="Friendship">
                                <span class="label label-default">Friendship</span>
                            </label>
                        </div>
                    </div>

                    <div class="col-lg-2">
                        <div class="checkbox checkbox-success">
                            <?php echo $this->formRow($form->get('Stacks')); ?>
                            <label for="Stacks">
                                <span class="label label-default">Stacks</span>
                            </label>
                        </div>
                        <div class="checkbox checkbox-success">
                            <?php echo $this->formRow($form->get('PremiumStacks')); ?>
                            <label for="PremiumStacks">
                                <span class="label label-default">Premium Stacks</span>
                            </label>
                        </div>
                        <div class="checkbox checkbox-success">
                            <?php echo $this->formRow($form->get('Charm')); ?>
                            <label for="Charm">
                                <span class="label label-default">Charm</span>
                            </label>
                        </div>
                    </div>

                    <div class="col-lg-2">
                        <div class="checkbox checkbox-success">
                            <?php echo $this->formRow($form->get('Gold')); ?>
                            <label for="Gold">
                                <span class="label label-default">Gold</span>
                            </label>
                        </div>
                        <div class="checkbox checkbox-success">
                            <?php echo $this->formRow($form->get('SterlingSilver')); ?>
                            <label for="SterlingSilver">
                                <span class="label label-default">SterlingSilver</span>
                            </label>
                        </div>
                        <div class="checkbox checkbox-success">
                            <?php echo $this->formRow($form->get('Personalisable')); ?>
                            <label for="Personalisable">
                                <span class="label label-default">Personalisable</span>
                            </label>
                        </div>
                    </div>

                    <div class="col-lg-2">
                        <div class="checkbox checkbox-success">
                            <?php echo $this->formRow($form->get('Engraved')); ?>
                            <label for="Engraved">
                                <span class="label label-default">Engraved</span>
                            </label>
                        </div>
                        <div class="checkbox checkbox-success">
                            <?php echo $this->formRow($form->get('Weddings')); ?>
                            <label for="Weddings">
                                <span class="label label-default">Weddings</span>
                            </label>
                        </div>
                        <div class="checkbox checkbox-success">
                            <?php echo $this->formRow($form->get('Birthdays')); ?>
                            <label for="Birthdays">
                                <span class="label label-default">Birthdays</span>
                            </label>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="checkbox checkbox-success">
                            <?php echo $this->formRow($form->get('ExcludeFromTrade')); ?>
                            <label for="ExcludeFromTrade">
                                <span class="label label-default">Exclude Trade</span>
                            </label>
                        </div>
                        <div class="checkbox checkbox-success">
                            <?php echo $this->formRow($form->get('PartOfTradePack')); ?>
                            <label for="PartOfTradePack">
                                <span class="label label-default">Trade Pack Quantity</span>
                            </label>
                        </div>
                        <?php echo $this->formRow($form->get('QtyInTradePack')->setValue(0)); ?>
                    </div>

                </div>

            </div>

        </div>


    </fieldset>


    <fieldset>
        <legend>Raw Materials</legend>
        <?php echo $this->UIProductRawMaterialsManager($productId); ?>
    </fieldset>

    <!-- /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// --->

    <fieldset>
        <legend>Labour</legend>
        <?php echo $this->UIProductLabourManager($productId); ?>
    </fieldset>

    <!-- /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// --->

    <fieldset>
        <legend>Dispatch</legend>
    </fieldset>

    <!-- /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// --->

    <fieldset>
        <legend>Packaging</legend>
        <?php echo $this->UIProductPackagingManager($productId); ?>
    </fieldset>

    <!-- /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// --->

    <fieldset>
        <legend>Financials</legend>

    </fieldset>

    <div class="form-group">
        <div class="col-lg-3 col-lg-offset-9">
            <a href="/business-admin/raw-material-types" type="reset" class="btn btn-default">Cancel</a>
            <?php echo $this->formSubmit($form->get('submit')); ?>
        </div>
    </div>

    <!-- /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// --->

    <div class="modal fade" id="buildProductName" tabindex="-1" role="dialog" aria-labelledby="buildProductNameLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="buildProductNameLabel">Build Product Name</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label class="col-lg-3 control-label" for="Name">Name:</label>
                        <div class="col-lg-9">
                            <?php echo $this->formRow($form->get('Name')); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-3 control-label" for="NameCharm">Choose Charm:</label>
                        <div class="col-lg-9">
                            <?php echo $this->formRow($form->get('NameCharm')); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-3 control-label" for="NameCrystal">Choose Crystal:</label>
                        <div class="col-lg-9">
                            <?php echo $this->formRow($form->get('NameCrystal')); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-3 control-label" for="NameColour">Choose Colour:</label>
                        <div class="col-lg-9">
                            <?php echo $this->formRow($form->get('NameColour')); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-3 control-label" for="NameLength">Choose Length:</label>
                        <div class="col-lg-9">
                            <?php echo $this->formRow($form->get('NameLength')); ?>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" id="buildProductNameSave" class="btn btn-success" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <!-- /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// --->

    <?php echo $this->form()->closeTag(); ?>

</div>

<script type="application/javascript" src="/js/jqGrid/bootstrap/integrations/amdsupport/js/i18n/grid.locale-en.js?v=1"></script>
<script type="application/javascript" src="/js/jqGrid/js/trirand/jquery.jqGrid.min.js"></script>
<script>
    subtotals = {};
    subtotals.rawMaterials = 0;
    subtotals.labour = 0;
    subtotals.dispatchPack = 0;
    subtotals.packaging = 0;
    onclickSubmitLocal = function (options, postdata) {
        console.log(postdata);
        this.processing = true;
        return {};
    };

    $(document).ready(function () {
        $('#products').submit(function () {
            $('#rawMaterialsGridData').val(JSON.stringify($("#rawMaterialGrid").jqGrid('getGridParam', 'data')));
        });
        //=============================================
        $('#DescRadio1,#DescRadio2,#DescRadio3').change(function (elem) {
            $('#DescBlock').find("span").each(function (index) {
                $(this).removeClass().addClass('label label-default');
            });
            switch (elem.currentTarget.id) {
                case 'DescRadio1':
                    $(elem.currentTarget).next().children().switchClass('label-default', 'label-danger', 500, 'easeInOutQuad');
                    break;
                case 'DescRadio2':
                    $(elem.currentTarget).next().children().switchClass('label-default', 'label-warning', 500, 'easeInOutQuad');
                    break;
                case 'DescRadio3':
                    $(elem.currentTarget).next().children().switchClass('label-default', 'label-success', 500, 'easeInOutQuad');
                    break;
            }
        });
        //=============================================
        $('#optionsBlock input:checkbox').each(function () {
            $(this).change(function () {
                if ($(this).is(':checked')) {
                    $(this).next().children().switchClass('label-default', 'label-success', 500, 'easeInOutQuad');
                } else {
                    $(this).next().children().switchClass('label-success', 'label-default', 500, 'easeInOutQuad');
                }
            });
        });
        //=============================================
        $('#ProductName').focus(function () {
            $('#buildProductName').modal('show');
            $('#Name').focus();
        });
        $('#buildProductName').on('hidden.bs.modal', function () {
            $('#SKU').focus();
        });
        //=============================================
        $("#IntroDate").datepicker({
            autoclose: true,
            dateFormat: "yy-mm-dd",
            format: 'dd-mm-yy',
            altFormat: "yy-mm-dd",
            orientation: 'bottom',
            changeMonth: true,
            changeYear: true
        });
        //=============================================
        $("#Name").bind('keyup', function () {
            concatName();
        });
        $("#Charm").bind('change', function () {
            concatName();
        });
        $("#Chrystal").bind('change', function () {
            concatName();
        });
        $("#Colour").bind('change', function () {
            concatName();
        });
        $("#Length").bind('change', function () {
            concatName();
        });
        $("#buildProductNameSave").click(function () {
            concatName();
        });
        concatName = function () {
            $("#ProductName").val($("#Name").val());
            if ($("#NameCharm").val()) {
                $("#ProductName").val($("#ProductName").val() + ' - ' + $("#NameCharm").val());
            }
            if ($("#NameCrystal").val()) {
                $("#ProductName").val($("#ProductName").val() + ' - ' + $("#NameCrystal").val());
            }
            if ($("#NameColour").val()) {
                $("#ProductName").val($("#ProductName").val() + ' - ' + $("#NameColour").val());
            }
            if ($("#NameLength").val()) {
                $("#ProductName").val($("#ProductName").val() + ' - ' + $("#NameLength").val());
            }
        };
    });
</script>
