<?php
echo $this->UIPageTitleFormatter($this->navigation('navigation')->findActive('navigation')['page']->label);

$form->setAttribute('action', $this->url('business-admin/products', array('action' => 'add')));
$form->setAttributes(array('class' => 'form-horizontal'));
$form->prepare();
?>

<div class="well bs-component">

    <?php echo$this->form()->openTag($form) ?>

    <fieldset>
        <legend>Add New Product</legend>

        <?php echo $this->formHidden($form->get('ProductID')->setValue(0)) ?>

        <div class="form-group">
            <label class="col-lg-2 control-label" for="ProductName">Product Name:</label>
            <div class="col-lg-10">
                <?php echo $this->formRow($form->get('ProductName')); ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-lg-2 control-label" for="SKU">SKU:</label>
            <div class="col-lg-10">
                <?php echo $this->formRow($form->get('SKU')); ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-lg-2 control-label" for="CollectionID">Collection:</label>
            <div class="col-lg-10">
                <?php echo $this->formRow($form->get('CollectionID')); ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-lg-2 control-label" for="ProductTypeID">Product Type:</label>
            <div class="col-lg-10">
                <?php echo $this->formRow($form->get('ProductTypeID')); ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-lg-2 control-label" for="IntroDate">Date Introduced:</label>
            <div class="col-lg-10">
                <?php echo $this->formRow($form->get('IntroDate')->setValue(date('Y-m-d'))); ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-lg-2 control-label" for="Strands">Strands:</label>
            <div class="col-lg-10">
                <?php echo $this->formRow($form->get('Strands')); ?>
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-10 col-lg-offset-2">
                <a href="/business-admin/raw-material-types" type="reset" class="btn btn-default btn-sm">Cancel</a>
                <?php echo $this->formSubmit($form->get('submit')); ?>
            </div>
        </div>
    </fieldset>

    <!-- /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// --->

    <div class="modal fade" id="buildProductName" tabindex="-1" role="dialog" aria-labelledby="buildProductName">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Build Product Name</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label class="col-lg-3 control-label" for="Name">Name:</label>
                        <div class="col-lg-9">
                            <?php echo $this->formRow($form->get('Name')); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-3 control-label" for="NameCharm">Choose Charm:</label>
                        <div class="col-lg-9">
                            <?php echo $this->formRow($form->get('NameCharm')); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-3 control-label" for="NameCrystal">Choose Crystal:</label>
                        <div class="col-lg-9">
                            <?php echo $this->formRow($form->get('NameCrystal')); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-3 control-label" for="NameColour">Choose Colour:</label>
                        <div class="col-lg-9">
                            <?php echo $this->formRow($form->get('NameColour')); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-3 control-label" for="NameLength">Choose Length:</label>
                        <div class="col-lg-9">
                            <?php echo $this->formRow($form->get('NameLength')); ?>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" id="buildProductNameSave" class="btn btn-success" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <?php echo $this->form()->closeTag(); ?>

</div>

<script>
    $(document).ready(function () {
        $('#ProductName').focus(function () {
            $('#buildProductName').modal('show');
            $('#Name').focus();
        });
        $('#buildProductName').on('hidden.bs.modal', function () {
            $('#SKU').focus();
        });
        $("#IntroDate").datepicker({
            autoclose: true,
            dateFormat: "yy-mm-dd",
            format: 'dd-mm-yy',
            altFormat: "yy-mm-dd",
            orientation: 'bottom',
            changeMonth: true,
            changeYear: true
        });
        $("#Name").bind('keyup', function () {
            concatName();
        });
        $("#Charm").bind('change', function () {
            concatName();
        });
        $("#Chrystal").bind('change', function () {
            concatName();
        });
        $("#Colour").bind('change', function () {
            concatName();
        });
        $("#Length").bind('change', function () {
            concatName();
        });
        $("#buildProductNameSave").click(function () {
            concatName();
        });
        concatName = function () {
            $("#ProductName").val($("#Name").val());
            if ($("#NameCharm").val()) {
                $("#ProductName").val($("#ProductName").val() + ' - ' + $("#NameCharm").val());
            }
            if ($("#NameCrystal").val()) {
                $("#ProductName").val($("#ProductName").val() + ' - ' + $("#NameCrystal").val());
            }
            if ($("#NameColour").val()) {
                $("#ProductName").val($("#ProductName").val() + ' - ' + $("#NameColour").val());
            }
            if ($("#NameLength").val()) {
                $("#ProductName").val($("#ProductName").val() + ' - ' + $("#NameLength").val());
            }
        };
    });
</script>
