<?php
echo $this->partial('annie-haak/partial/productsNavbar.phtml');

echo $this->UIPageTitleFormatter($this->navigation('navigation')->findActive('navigation')['page']->label);

#dump($form->getObject());
#exit();

$productId = $form->getObject()->ProductID;
$currentUrl = ($form->getObject()->CurrentURL) ? $form->getObject()->CurrentURL : '';
$oldUrl = ($form->getObject()->OldURL) ? $form->getObject()->OldURL : '';

$form->setAttribute('action', $this->url('business-admin/products', array('action' => 'add')));
$form->setAttributes(array('class' => 'form-horizontal'));
$form->prepare();

echo $this->form()->openTag($form)
?>

<div class="well bs-component">

    <fieldset>

        <legend>Edit Product</legend>

        <?php echo $this->formHidden($form->get('ProductID')) ?>

        <div class="form-group">
            <div class="col-md-10 col-md-offset-2">
                <?php if ($form->getObject()->Current == 0) : ?>
                    <div class="alert alert-danger text-center bold">
                        Not Live
                    </div>
                <?php else: ?>
                    <div class="alert alert-success text-center bold">
                        Currently Live
                    </div>
                <?php endif; ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label" for="ProductName">Product Name:</label>
            <div class="col-md-10">
                <?php echo $this->formRow($form->get('ProductName')); ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label" for="SKU">SKU:</label>
            <div class="col-md-10">
                <?php echo $this->formRow($form->get('SKU')); ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label" for="CollectionID">Collection:</label>
            <div class="col-md-10">
                <?php echo $this->formRow($form->get('CollectionID')); ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label" for="ProductTypeID">Product Type:</label>
            <div class="col-md-10">
                <?php echo $this->formRow($form->get('ProductTypeID')); ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label" for="Strands">Strands:</label>
            <div class="col-md-10">
                <?php echo $this->formRow($form->get('Strands')); ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label" for="IntroDate">Date Introduced:</label>
            <div class="col-md-10">
                <?php echo $this->formRow($form->get('IntroDate')); ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label" for="MinsToBuild">Mins To Build:</label>
            <div class="col-md-10">
                <?php echo $this->formRow($form->get('MinsToBuild')); ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label" for="QtyOrderedLastPeriod">Sold Last Period:</label>
            <div class="col-md-10">
                <?php echo $this->formRow($form->get('QtyOrderedLastPeriod')); ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label" for="CurrentURL">Current URL:</label>
            <div class="col-md-9">
                <?php echo $this->formRow($form->get('CurrentURL')); ?>
            </div>
            <div class="col-md-1">
                <a href="#" title="View image">
                    <img src="<?php echo $currentUrl; ?>" id="currentUrlThumb" class="img-thumbnail"  />
                </a>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label" for="OldURL">Old URL:</label>
            <div class="col-md-9">
                <?php echo $this->formRow($form->get('OldURL')); ?>
            </div>
            <div class="col-md-1">
                <a href="#" title="View image">
                    <img src="<?php echo $oldUrl; ?>" id="oldUrlThumb" class="img-thumbnail"  />
                </a>
            </div>
        </div>

        <div class="form-group" id="DescBlock">
            <label class="col-md-2 control-label" for="Description">Description:</label>
            <div class="col-md-10">
                <?php echo $this->formRow($form->get('Description')); ?>
            </div>
            <div class="col-md-10 col-md-offset-2">
                <div class="radio radio-danger pull-left margin-right-5">
                    <?php if ($form->getObject()->DescriptionStatus == 0) : ?>
                        <input name="DescriptionStatus" id="DescRadio1" value="0" type="radio" checked="checked" />
                        <label for="DescRadio1">
                            <span class="label label-danger">Needs Description</span>
                        </label>
                    <?php else: ?>
                        <input name="DescriptionStatus" id="DescRadio1" value="0" type="radio" />
                        <label for="DescRadio1">
                            <span class="label label-default">Needs Description</span>
                        </label>
                    <?php endif; ?>
                </div>
                <div class="radio radio-warning pull-left margin-right-5">
                    <?php if ($form->getObject()->DescriptionStatus == 1) : ?>
                        <input name="DescriptionStatus" id="DescRadio2" value="1" type="radio" checked="checked" />
                        <label for="DescRadio2">
                            <span class="label label-warning">Pending Approval</span>
                        </label>
                    <?php else: ?>
                        <input name="DescriptionStatus" id="DescRadio2" value="1" type="radio" />
                        <label for="DescRadio2">
                            <span class="label label-default">Pending Approval</span>
                        </label>
                    <?php endif; ?>
                </div>
                <div class="radio radio-success pull-left">
                    <?php if ($form->getObject()->DescriptionStatus == 2) : ?>
                        <input name="DescriptionStatus" id="DescRadio3" value="2" type="radio" checked="checked" />
                        <label for="DescRadio3">
                            <span class="label label-success">Approved</span>
                        </label>
                    <?php else: ?>
                        <input name="DescriptionStatus" id="DescRadio3" value="2" type="radio" />
                        <label for="DescRadio3">
                            <span class="label label-default">Approved</span>
                        </label>
                    <?php endif; ?>
                </div>

            </div>
        </div>

        <div class="form-group">

            <label class="col-md-2 control-label" for="Description">Options:</label>

            <div class="col-md-10">

                <div class="row" id="optionsBlock">

                    <div class="col-md-2">
                        <div class="checkbox checkbox-success">
                            <?php echo $this->formRow($form->get('KeyPiece')); ?>
                            <label for="KeyPiece">
                                <span class="label label-default">Key Piece</span>
                            </label>
                        </div>
                        <div class="checkbox checkbox-success">
                            <?php echo $this->formRow($form->get('Accessories')); ?>
                            <label for="Accessories">
                                <span class="label label-default">Accessories</span>
                            </label>
                        </div>
                        <div class="checkbox checkbox-success">
                            <?php echo $this->formRow($form->get('Friendship')); ?>
                            <label for="Friendship">
                                <span class="label label-default">Friendship</span>
                            </label>
                        </div>
                    </div>

                    <div class="col-md-2">
                        <div class="checkbox checkbox-success">
                            <?php echo $this->formRow($form->get('Stacks')); ?>
                            <label for="Stacks">
                                <span class="label label-default">Stacks</span>
                            </label>
                        </div>
                        <div class="checkbox checkbox-success">
                            <?php echo $this->formRow($form->get('PremiumStacks')); ?>
                            <label for="PremiumStacks">
                                <span class="label label-default">Premium Stacks</span>
                            </label>
                        </div>
                        <div class="checkbox checkbox-success">
                            <?php echo $this->formRow($form->get('Charm')); ?>
                            <label for="Charm">
                                <span class="label label-default">Charm</span>
                            </label>
                        </div>
                    </div>

                    <div class="col-md-2">
                        <div class="checkbox checkbox-success">
                            <?php echo $this->formRow($form->get('Gold')); ?>
                            <label for="Gold">
                                <span class="label label-default">Gold</span>
                            </label>
                        </div>
                        <div class="checkbox checkbox-success">
                            <?php echo $this->formRow($form->get('SterlingSilver')); ?>
                            <label for="SterlingSilver">
                                <span class="label label-default">SterlingSilver</span>
                            </label>
                        </div>
                        <div class="checkbox checkbox-success">
                            <?php echo $this->formRow($form->get('Personalisable')); ?>
                            <label for="Personalisable">
                                <span class="label label-default">Personalisable</span>
                            </label>
                        </div>
                    </div>

                    <div class="col-md-2">
                        <div class="checkbox checkbox-success">
                            <?php echo $this->formRow($form->get('Engraved')); ?>
                            <label for="Engraved">
                                <span class="label label-default">Engraved</span>
                            </label>
                        </div>
                        <div class="checkbox checkbox-success">
                            <?php echo $this->formRow($form->get('Weddings')); ?>
                            <label for="Weddings">
                                <span class="label label-default">Weddings</span>
                            </label>
                        </div>
                        <div class="checkbox checkbox-success">
                            <?php echo $this->formRow($form->get('Birthdays')); ?>
                            <label for="Birthdays">
                                <span class="label label-default">Birthdays</span>
                            </label>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="checkbox checkbox-success">
                            <?php echo $this->formRow($form->get('ExcludeFromTrade')); ?>
                            <label for="ExcludeFromTrade">
                                <span class="label label-default">Exclude Trade</span>
                            </label>
                        </div>
                        <div class="checkbox checkbox-success">
                            <?php echo $this->formRow($form->get('PartOfTradePack')); ?>
                            <label for="PartOfTradePack">
                                <span class="label label-default">Trade Pack Quantity</span>
                            </label>
                        </div>
                        <?php echo $this->formRow($form->get('QtyInTradePack')); ?>
                    </div>

                </div>

            </div>

        </div>


    </fieldset>


    <fieldset>
        <legend>Raw Materials</legend>
        <?php echo $this->partial('annie-haak/partial/productsRawMaterialsManager.phtml', array('productId' => $productId)); ?>
    </fieldset>

    <!-- /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// --->

    <fieldset>
        <legend>Labour</legend>
        <?php echo $this->partial('annie-haak/partial/productsLabourManager.phtml', array('productId' => $productId)); ?>
    </fieldset>

    <!-- /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// --->

    <fieldset>
        <legend>Dispatch</legend>
    </fieldset>

    <!-- /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// --->

    <fieldset>
        <legend>Packaging</legend>
        <?php echo $this->partial('annie-haak/partial/productsPackagingManager.phtml', array('productId' => $productId)); ?>
    </fieldset>

    <!-- /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// --->

    <fieldset>
        <legend>Financials</legend>
        <?php echo $this->partial('annie-haak/partial/productsFinancials.phtml'); ?>
    </fieldset>

    <div class="form-group">
        <div class="col-md-3 col-md-offset-9">
            <a href="/business-admin/raw-material-types" type="reset" class="btn btn-default">Cancel</a>
            <?php echo $this->formSubmit($form->get('submit')); ?>
        </div>
    </div>

    <!-- /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// --->

    <?php echo $this->partial('annie-haak/partial/productsModals.phtml'); ?>

    <!-- /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// --->

    <?php echo $this->form()->closeTag(); ?>

</div>

<script type="application/javascript" src="/js/jqGrid/bootstrap/integrations/amdsupport/js/i18n/grid.locale-en.js?v=1"></script>
<script type="application/javascript" src="/js/jqGrid/js/trirand/jquery.jqGrid.min.js?v=1"></script>
<script type="application/javascript" src="/js/productsAddEdit.js?v=1"></script>

