<?php
echo $this->UIPageTitleFormatter($this->navigation('navigation')->findActive('navigation')['page']->label);
echo $this->UIAccessControlButtons($_SESSION['AnnieHaak']['storage']['userInfo']['roleLevel'], 'add', '/business-admin/products/add', 'Add new Product');
echo '<a href="/business-admin/products" class="btn btn-info btn-sm pull-left"><span class="glyphicon glyphicon-refresh"></span> Reload All</a>';
?>
<div class="clearfix"></div>
<p>&nbsp;</p>
<div style="width: 95%; margin: 0 auto;">
    <table id="jqGrid" class="table table-striped table-hover"></table>
    <div id="jqGridPager"></div>
</div>
<p>&nbsp;</p>

<script type="text/javascript">
    $(document).ready(function () {
        $.jgrid.defaults.responsive = true;
        $.jgrid.defaults.styleUI = 'Bootstrap';
        datePick = function (elem)
        {
            jQuery(elem).datepicker({
                autoclose: true,
                dateFormat: "yy-mm-dd",
                format: 'dd-mm-yy',
                altFormat: "yy-mm-dd",
                orientation: 'bottom',
                changeMonth: true,
                changeYear: true
            });
        };
        function dateCheck(value, colname) {
            var re = /^\d{4}-\d{1,2}-\d{1,2}$/;
            if (re.test(value)) {
                return [true, ""];
            }
            else {
                return [false, "Date format for " + colname + " wrong: YYYY-MM-DD"];
            }
        }
        $("#jqGrid").jqGrid({
            url: '/business-admin/products/jsonData<?php echo $productActioned; ?>',
            sortname: 'ProductName',
            mtype: "GET",
            styleUI: 'Bootstrap',
            datatype: "json",
            viewrecords: true,
            loadonce: false,
            height: 'auto',
            loadui: 'enable',
            viewsortcols: [true, 'vertical', true],
            loadComplete: function (data) {
<?php if (strlen($productActioned)): ?>
                    $("#jqGrid").setSelection(data.rows[0]['ProductID'], true);
<?php endif; ?>
            },
            colModel: [
                {
                    label: 'ID',
                    name: 'ProductID',
                    key: true,
                    hidden: true
                },
                {
                    label: 'Product Name',
                    name: 'ProductName',
                    align: 'left',
                    sortable: true,
                    width: 375,
                    search: true,
                    searchrules: {
                        required: true
                    },
                    searchoptions: {
                        sopt: ["eq", "cn", "bw", "ew"]
                    },
                },
                {
                    label: 'Product Type',
                    name: 'ProductTypeName',
                    align: 'left',
                    sortable: true,
                    width: 100,
                    search: true,
                    searchrules: {
                        required: true
                    },
                    searchoptions: {
                        sopt: ["eq", "cn", "bw", "ew"]
                    }
                },
                {
                    label: 'Collection Name',
                    name: 'ProductCollectionName',
                    align: 'left',
                    sortable: true,
                    width: 175,
                    search: true,
                    searchrules: {
                        required: true
                    },
                    searchoptions: {
                        sopt: ["eq", "cn", "bw", "ew"]
                    }
                },
                {
                    label: 'Current',
                    name: 'CurrentHTML',
                    index: 'Current',
                    align: 'left',
                    sortable: true,
                    width: 75,
                    search: true,
                    stype: 'select',
                    searchrules: {
                        required: true
                    },
                    searchoptions: {
                        sopt: ["eq"],
                        value: ":All;1:Yes;0:No"
                    }
                },
                {
                    label: 'Introduced',
                    name: 'IntroDate',
                    formatter: 'date',
                    formatoptions: {
                        srcformat: 'Y-m-d',
                        newformat: 'Y M d',
                        defaultValue: null
                    },
                    width: 100,
                    sortable: true,
                    align: 'left',
                    search: true,
                    sorttype: "text",
                    searchrules: {
                        custom: true,
                        custom_func: dateCheck
                    },
                    searchoptions: {
                        dataInit: datePick,
                        sopt: ["eq", "lt", "gt"],
                        placeholder: 'yyyy-mm-dd'
                    },
                },
                {
                    label: 'Copy',
                    name: 'DuplicateHTML',
                    align: 'center',
                    title: 'Copy',
                    width: 75,
                    sortable: false,
                    search: false
                },
                {
                    label: 'Edit',
                    name: 'EditHTML',
                    align: 'center',
                    title: 'Edit',
                    width: 75,
                    sortable: false,
                    search: false
                },
                {
                    label: 'Delete',
                    name: 'DeleteHTML',
                    align: 'center',
                    width: 75,
                    sortable: false,
                    search: false
                }
            ],
            rownumbers: true,
            rownumWidth: 20,
            rowNum: 15,
            rowList: [15, 30, 50],
            pager: "#jqGridPager"
        });
        $("#jqGrid").navGrid('#jqGridPager',
                {
                    search: true,
                    view: false,
                    del: false,
                    edit: false,
                    add: false,
                    view: true
                },
                {}, // edit options
                {}, // add options
                {}, // delete options
                {
                    multipleSearch: true
                }
        );
    });</script>
<script type="application/javascript" src="/js/jqGrid/bootstrap/integrations/amdsupport/js/i18n/grid.locale-en.js?v=1"></script>
<script type="application/javascript" src="/js/jqGrid/js/trirand/jquery.jqGrid.min.js"></script>
