<?php
echo $this->UIPageTitleFormatter($this->navigation('navigation')->findActive('navigation')['page']->label);
echo $this->UIAccessControlButtons($_SESSION['AnnieHaak']['storage']['userInfo']['roleLevel'], 'add', '/business-admin/products/add', 'Add new Product');
?>

<a href="/business-admin/product-types" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-refresh"></span> Refresh</a>
