<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8" />

        <?php
        echo $this->headTitle();
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Styles -->
        <?php
        $version = 1;
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => '/img/favicon.ico'))
                #->appendStylesheet($this->basePath('bower_components/bootstrap/dist/css/bootstrap.min.css?v=' . $version), 'all')
                ->appendStylesheet($this->basePath('bower_components/bootswatch-dist/css/bootstrap.min.css?v=' . $version), 'all')
                ->appendStylesheet($this->basePath('bower_components/jquery-ui/themes/cupertino/jquery-ui.min.css?v=' . $version), 'all')
                ->appendStylesheet($this->basePath('bower_components/font-awesome/css/font-awesome.min.css?v=' . $version), 'all')
                ->appendStylesheet($this->basePath('css/awesome-bootstrap-checkbox.css?v=' . $version), 'all')
                ->appendStylesheet($this->basePath('bower_components/jqGrid/css/ui.jqgrid-bootstrap.css?v=' . $version), 'all')
                ->appendStylesheet($this->basePath('css/style.css?v=' . $version), 'all')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->appendFile($this->basePath('bower_components/jquery/dist/jquery.min.js?v=' . $version))
                ->appendFile($this->basePath('bower_components/jquery-ui/jquery-ui.min.js?v=' . $version))
                ->appendFile($this->basePath('bower_components/jquery.pwstrength/jquery.pwstrength.min.js?v=' . $version))
                ->appendFile($this->basePath('bower_components/bootstrap/dist/js/bootstrap.min.js?v=' . $version))
                ->appendFile($this->basePath('js/numericInput.min.js?v=' . $version))
        ?>
    </head>
    <body>

        <!-- Navigation -->
        <?php echo $this->partial('annie-haak/partial/mainMenu.phtml'); ?>
        <!--/ Navigation -->

        <div class="container" id="container">
            <!-- Breadcrumbs -->
            <?php
            if ((isset($_SESSION["AnnieHaak"]['storage']['userInfo']['loggedIn']))) {
                echo $this->partial('annie-haak/partial/breadcrumbs.phtml');
            }
            ?>
            <!--/ Breadcrumbs -->

            <!-- Feedback messages -->
            <div class="">
                <?php
                $flash = $this->flashMessenger();
                $flash->setMessageOpenFormat('<div%s><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><ul><li>')
                        ->setMessageSeparatorString('</li><li>')
                        ->setMessageCloseString('</li></ul></div>');

                echo $flash->render('error', array('alert', 'alert-dismissible', 'alert-danger'));
                echo $flash->render('info', array('alert', 'alert-dismissible', 'alert-info'));
                echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
                echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
                ?>
            </div>
            <div class="clearfix"></div>
            <!-- Feedback messages -->

            <?php echo $this->content; ?>

        </div> <!-- /container -->


        <footer class="footer hidden-print">
            <div class="container">
                <p class="text-muted">&copy; 2016 - <?php echo date('Y') ?> by Annie Haak. <?php echo $this->translate('All rights reserved.') ?></p>
            </div>
        </footer>

        <?php echo $this->inlineScript(); ?>

    </body>
</html>