<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Annie Haak Administration'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery.min.js'))
                ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>

    </head>
    <body>

        <!-- Navigation -->
        <?php 
            echo $this->partial('annie-haak/partial/menu.phtml');
        ?>
        <!--/ Navigation -->

        <!-- Breadcrumbs -->
        <?php if((isset($_SESSION["AnnieHaak"]['storage']['loggedIn'])))
        {
                echo $this->partial('annie-haak/partial/breadcrumbs.phtml');
        }
        ?>
        <!--/ Breadcrumbs -->

        <div class="container" id="container">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
            
        <footer class="footer">
            <div class="container">
                <p class="text-muted">&copy; 2015 - <?php echo date('Y') ?> by Annie Haak. <?php echo $this->translate('All rights reserved.') ?></p>
            </div>
        </footer>

<?php echo $this->inlineScript() ?>

<!--
<pre>
<?php
echo var_dump($this->messages);
?>
</pre>
-->

    </body>
</html>