<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">

        <?php
        echo $this->headTitle();
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Styles -->
        <?php
        $version = 1;
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => '/img/favicon.ico'))
                #->appendStylesheet($this->basePath('bower_components/bootstrap/dist/css/bootstrap.min.css?v=' . $version), 'all')
                ->appendStylesheet($this->basePath('bower_components/bootswatch-dist/css/bootstrap.min.css?v=' . $version), 'all')
                ->appendStylesheet($this->basePath('bower_components/jquery-ui/themes/cupertino/jquery-ui.min.css?v=' . $version), 'all')
                ->appendStylesheet($this->basePath('bower_components/font-awesome/css/font-awesome.min.css?v=' . $version), 'all')
                ->appendStylesheet($this->basePath('css/awesome-bootstrap-checkbox.css?v=' . $version), 'all')
                ->appendStylesheet($this->basePath('bower_components/jqGrid/css/ui.jqgrid-bootstrap.css?v=' . $version), 'all')
                ->appendStylesheet($this->basePath('css/style.css?v=' . $version), 'all')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->appendFile($this->basePath('bower_components/jquery/dist/jquery.min.js?v=' . $version))
                ->appendFile($this->basePath('bower_components/jquery-ui/jquery-ui.min.js?v=' . $version))
                ->appendFile($this->basePath('bower_components/jquery.pwstrength/jquery.pwstrength.min.js?v=' . $version))
                ->appendFile($this->basePath('bower_components/bootstrap/dist/js/bootstrap.min.js?v=' . $version))
                ->appendFile($this->basePath('js/numericInput.min.js?v=' . $version))
        ?>
        <style>
            html, body{
                background-color: #ffffff;
                color: #000;
            }
            table, tr, td, .table{
                background-color: #ffffff;
            }
        </style>
    </head>
    <body>

        <div class="container" id="container">
            <?php echo $this->content; ?>
        </div>

    </body>
</html>