<?php
echo $this->UIPageTitleFormatter($this->navigation('navigation')->findActive('navigation')['page']->label);

$form->setAttribute('action', $this->url('business-admin/raw-material-types', array('action' => 'add')));
$form->setAttributes(array('class' => 'form-horizontal'));
$form->prepare();
?>

<div class="well bs-component">

    <?php echo $this->form()->openTag($form); ?>

    <fieldset><legend>Add Raw Material Type</legend>

        <?php echo $this->formHidden($form->get('RMTypeID')->setValue(0)); ?>

        <div class="form-group">
            <label class="col-md-2 control-label" for="RMTypeName">Raw Material Type Name:</label><div class="col-md-10">
                <?php echo $this->formRow($form->get('RMTypeName')); ?>
            </div></div>

        <div class="form-group">
            <div class="col-md-10 col-md-offset-2">
                <a href="/business-admin/raw-material-types" type="reset" class="btn btn-default btn-sm">Cancel</a>
                <?php echo $this->formSubmit($form->get('submit')); ?>
            </div></div>

    </fieldset>

    <?php echo $this->form()->closeTag(); ?>

</div>
