<?php

echo $this->UIPageTitleFormatter($this->navigation('navigation')->findActive('navigation')['page']->label);

$form = $this->form;
$form->setAttribute('action', $this->url('business-admin/raw-material-types', array('action' => 'edit', 'id' => $this->id,)));
$form->setAttributes(array('class' => 'form-horizontal'));
$form->prepare();

echo '<div class="well bs-component">';

echo $this->form()->openTag($form);

echo '<fieldset><legend>Edit Raw Material Types</legend>';

echo $this->formHidden($form->get('RMTypeID'));

echo '<div class="form-group">';
echo '<label class="col-md-2 control-label" for="RMTypeName">Raw Material Type Name:</label><div class="col-md-10">';
echo $this->formRow($form->get('RMTypeName'));
echo '</div></div>';

echo '<div class="form-group">';
echo '<div class="col-md-10 col-md-offset-2">';
echo '<a href="/business-admin/raw-material-types" type="reset" class="btn btn-default btn-sm">Cancel</a>';
$form->get('submit')->setAttribute('class', 'btn btn-warning btn-sm');
echo $this->formSubmit($form->get('submit'));
echo '</div></div>';

echo '</fieldset>';

echo $this->form()->closeTag();

echo '</div>';
