<?php
echo $this->UIPageTitleFormatter($this->navigation('navigation')->findActive('navigation')['page']->label);

$form = $this->form;
$form->setAttribute('action', $this->url('business-admin/raw-material-types', array('action' => 'edit', 'id' => $this->id,)));
$form->setAttributes(array('class' => 'form-horizontal'));
$form->prepare();
?>

<div class="well bs-component">

    <?php echo $this->form()->openTag($form); ?>

    <fieldset>

        <?php echo $this->formHidden($form->get('RMTypeID')); ?>

        <div class="form-group">
            <label class="col-md-2 control-label" for="RMTypeName">Raw Material Type Name:</label>
            <div class="col-md-10">
                <?php echo $this->formRow($form->get('RMTypeName')); ?>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-3 col-md-offset-9">
                <a href="/business-admin/raw-material-types" type="reset" class="btn btn-default btn-info-outline margin-right-10">Cancel</a>
                <?php echo $this->formSubmit($form->get('submit')); ?>
            </div>
        </div>

    </fieldset>

    <?php echo $this->form()->closeTag(); ?>

</div>
