<?php
echo $this->UIPageTitleFormatter($this->navigation('navigation')->findActive('navigation')['page']->label);
echo $this->UIAccessControlButtons($_SESSION['AnnieHaak']['storage']['userInfo']['roleLevel'], 'add', '/business-admin/raw-material-types/add', 'Add new Raw Material Type');
echo $this->partial('annie-haak/partial/reloadButton.phtml');

#http://www.guriddo.net/demo/bootstrap/
#http://www.trirand.com/jqgridwiki/doku.php?id=wiki:predefined_formatter
?>
<div class="clearfix"></div>
<p>&nbsp;</p>
<div style="width: 75%; margin: 0 auto;">
    <table id="jqGrid" class="table table-striped table-hover"></table>
    <div id="jqGridPager"></div>
</div>
<p>&nbsp;</p>

<?php echo $this->partial('annie-haak/partial/jqGridJS.phtml'); ?>
<script type="text/javascript">
    $.jgrid.defaults.responsive = true;
    $.jgrid.defaults.styleUI = 'Bootstrap';
    $(document).ready(function () {
        $("#jqGrid").jqGrid({
            url: '/business-admin/raw-material-types/jsonData',
            mtype: "GET",
            styleUI: 'Bootstrap',
            datatype: "json",
            viewrecords: true,
            loadonce: false,
            sortname: 'RMTypeName',
            height: 'auto',
            width: 750,
            viewsortcols: [true, 'vertical', true],
            colModel: [
                {
                    label: 'ID',
                    name: 'RMTypeID',
                    key: true,
                    hidden: true
                },
                {
                    label: 'Name',
                    name: 'RMTypeName',
                    align: 'left',
                    sortable: true,
                    width: 250,
                    search: true,
                    searchoptions: {
                        sopt: ["eq", "cn", "bw", "ew"]
                    }
                },
                {
                    label: 'Edit',
                    name: 'EditHTML',
                    align: 'center',
                    title: 'Edit',
                    width: 75,
                    sortable: false,
                    search: false
                },
                {
                    label: 'Delete',
                    name: 'DeleteHTML',
                    align: 'center',
                    width: 75,
                    sortable: false,
                    search: false
                }
            ],
            rownumbers: true,
            rownumWidth: 25,
            rowNum: 15,
            pager: "#jqGridPager"
        });
        $("#jqGrid").navGrid('#jqGridPager', {search: true, view: false, del: false, edit: false, add: false, view: true});
    });
</script>