<?php
echo $this->UIPageTitleFormatter($this->navigation('navigation')->findActive('navigation')['page']->label);

$form->setAttribute('action', $this->url('business-admin/raw-materials', array('action' => 'add')));
$form->setAttributes(array('class' => 'form-horizontal'));
$form->prepare();
?>

<div class="well bs-component">

    <?php echo $this->form()->openTag($form); ?>

    <fieldset>
        <legend>Add Raw Material Type</legend>

        <?php echo $this->formHidden($form->get('RawMaterialID')); ?>

        <div class="form-group">
            <label class="col-md-2 control-label" for="RawMaterialName">Raw Material Name:</label>
            <div class="col-md-10">
                <?php echo $this->formRow($form->get('RawMaterialName')); ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label" for="RawMaterialCode">Raw Material Code:</label>
            <div class="col-md-10">
                <?php echo $this->formRow($form->get('RawMaterialCode')); ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label" for="RMTypeID">Raw Material Type:</label>
            <div class="col-md-10">
                <?php echo $this->formRow($form->get('RMTypeID')); ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label" for="RMSupplierID">Raw Material Supplier:</label>
            <div class="col-md-10">
                <?php echo $this->formRow($form->get('RMSupplierID')); ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label" for="RawMaterialUnitCost">Raw Material Unit Cost:</label>
            <div class="col-md-10">
                <div class="input-group">
                    <div class="input-group-addon">£</div>
                    <?php echo $this->formRow($form->get('RawMaterialUnitCost')); ?>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label" for="DateLastChecked">Date Last Checked:</label>
            <div class="col-md-10">
                <?php echo $this->formRow($form->get('DateLastChecked')->setValue(date('Y-m-d'))); ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label" for="LastInvoiceNumber">Last Invoice Number:</label>
            <div class="col-md-10">
                <?php echo $this->formRow($form->get('LastInvoiceNumber')); ?>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-3 col-md-offset-9">
                <a href="/business-admin/raw-materials" type="reset" class="btn btn-default">Cancel</a>
                <?php echo $this->formSubmit($form->get('submit')); ?>
            </div>
        </div>

    </fieldset>

    <?php echo $this->form()->closeTag(); ?>

</div>

<script>
    $(function () {
        $("#DateLastChecked").datepicker({
            autoclose: true,
            dateFormat: "yy-mm-dd",
            format: 'dd-mm-yy',
            altFormat: "yy-mm-dd",
            orientation: 'bottom',
            changeMonth: true,
            changeYear: true
        });
    });
</script>
