<?php
echo $this->UIPageTitleFormatter($this->navigation('navigation')->findActive('navigation')['page']->label);
echo $this->UIAccessControlButtons($_SESSION['AnnieHaak']['storage']['userInfo']['roleLevel'], 'add', '/business-admin/raw-materials/add', 'Add new Raw Material');
echo '<a href="/business-admin/raw-materials" class="btn btn-info btn-sm pull-left"><span class="glyphicon glyphicon-refresh"></span> Refresh</a>';

#http://www.guriddo.net/demo/bootstrap/
#http://www.trirand.com/jqgridwiki/doku.php?id=wiki:predefined_formatter
?>
<div class="clearfix"></div>
<p>&nbsp;</p>
<div style="width: 95%; margin: 0 auto;">
    <table id="jqGrid" class="table table-striped table-hover"></table>
    <div id="jqGridPager"></div>
</div>
<p>&nbsp;</p>

<script type="application/javascript" src="/js/jqGrid/bootstrap/integrations/amdsupport/js/i18n/grid.locale-en.js?v=1"></script>
<script type="application/javascript" src="/js/jqGrid/js/trirand/jquery.jqGrid.min.js"></script>
<script type="text/javascript">
    $.jgrid.defaults.responsive = true;
    $.jgrid.defaults.styleUI = 'Bootstrap';
    datePick = function (elem)
    {
        jQuery(elem).datepicker({
            autoclose: true,
            dateFormat: "yy-mm-dd",
            format: 'dd-mm-yy',
            altFormat: "yy-mm-dd",
            orientation: 'bottom'
        });
    };
    $(document).ready(function () {
        $("#jqGrid").jqGrid({
            url: '/business-admin/raw-materials/jsonData',
            mtype: "GET",
            styleUI: 'Bootstrap',
            datatype: "json",
            viewrecords: true,
            loadonce: false,
            sortname: 'RawMaterialCode',
            height: 'auto',
            viewsortcols: [true, 'vertical', true],
            colModel: [
                {
                    label: 'ID',
                    name: 'RawMaterialID',
                    key: true,
                    hidden: true
                },
                {
                    label: 'Code',
                    name: 'RawMaterialCode',
                    align: 'left',
                    sortable: true,
                    width: 125,
                    search: true,
                    searchoptions: {
                        // show search options
                        sopt: ["eq", "cn", "bw", "ew"] // ge = greater or equal to, le = less or equal to, eq = equal to
                    }
                },
                {
                    label: 'Name',
                    name: 'RawMaterialName',
                    align: 'left',
                    sortable: true,
                    width: 250,
                    search: true,
                    searchoptions: {
                        sopt: ["eq", "cn", "bw", "ew"]
                    }
                },
                {
                    label: 'Cost',
                    name: 'RawMaterialUnitCost',
                    align: 'right',
                    sortable: true,
                    width: 75,
                    formatter: 'currency',
                    formatoptions: {
                        decimalSeparator: '.',
                        decimalPlaces: 4,
                        thousandsSeparator: ',',
                        prefix: '£'},
                    search: true,
                    searchoptions: {
                        sopt: ["eq", "lt", "le", "gt", "ge"]
                    }
                },
                {
                    label: 'Supplier',
                    name: 'RMSupplierName',
                    align: 'left',
                    sortable: true,
                    width: 150,
                    search: true,
                    searchoptions: {
                        sopt: ["eq", "cn", "bw", "ew"]
                    }
                },
                {
                    label: 'Type',
                    name: 'RMTypeName',
                    align: 'left',
                    sortable: true,
                    width: 175,
                    search: true,
                    searchoptions: {
                        sopt: ["eq", "cn", "bw", "ew"]
                    }
                },
                {
                    label: 'Last Checked',
                    name: 'DateLastChecked',
                    formatter: 'date',
                    formatoptions: {
                        srcformat: 'Y-m-d',
                        newformat: 'Y M d',
                        defaultValue: null
                    },
                    width: 100,
                    sortable: true,
                    align: 'left',
                    search: true,
                    sorttype: "text",
                    searchoptions: {
                        dataInit: datePick,
                        sopt: ["eq", "lt", "gt"]
                    }
                },
                {
                    label: 'Edit',
                    name: 'EditHTML',
                    align: 'center',
                    title: 'Edit',
                    width: 75,
                    sortable: false,
                    search: false
                },
                {
                    label: 'Delete',
                    name: 'DeleteHTML',
                    align: 'center',
                    width: 75,
                    sortable: false,
                    search: false
                }
            ],
            rownumbers: true,
            rownumWidth: 20,
            rowNum: 15,
            rowList: [15, 30, 50],
            pager: "#jqGridPager"
        });
        $("#jqGrid").navGrid('#jqGridPager', {search: true, view: false, del: false, edit: false, add: false, view: true});
    });
</script>