<?php
echo $this->UIPageTitleFormatter($this->navigation('navigation')->findActive('navigation')['page']->label);
echo $this->UIAccessControlButtons($_SESSION['AnnieHaak']['storage']['userInfo']['roleLevel'], 'add', '/business-admin/raw-materials/add', 'Add new Raw Material');
echo $this->partial('annie-haak/partial/reloadButton.phtml');

#http://www.guriddo.net/demo/bootstrap/
#http://www.trirand.com/jqgridwiki/doku.php?id=wiki:predefined_formatter
?>
<div class="clearfix"></div>
<p>&nbsp;</p>
<div style="width: 95%; margin: 0 auto;">
    <table id="jqGrid" class="table table-striped table-hover"></table>
    <div id="jqGridPager"></div>
</div>
<p>&nbsp;</p>

<script type="text/javascript">
    $(document).ready(function () {
        $.jgrid.defaults.responsive = true;
        $.jgrid.defaults.styleUI = 'Bootstrap';
        datePick = function (elem)
        {
            jQuery(elem).datepicker({
                autoclose: true,
                dateFormat: "yy-mm-dd",
                format: 'dd-mm-yy',
                altFormat: "yy-mm-dd",
                orientation: 'bottom',
                changeMonth: true,
                changeYear: true
            });
        };
        function dateCheck(value, colname) {
            var re = /^\d{4}-\d{1,2}-\d{1,2}$/;
            if (re.test(value)) {
                return [true, ""];
            }
            else {
                return [false, "Date format for " + colname + " wrong: YYYY-MM-DD"];
            }
        }
        $("#jqGrid").jqGrid({
            url: '/business-admin/raw-materials/jsonData',
            mtype: "GET",
            styleUI: 'Bootstrap',
            datatype: "json",
            viewrecords: true,
            loadonce: false,
            sortname: 'RawMaterialName',
            height: 'auto',
            viewsortcols: [true, 'vertical', true],
            rownumbers: true,
            rownumWidth: 25,
            rowNum: 15,
            pager: "#jqGridPager",
            colModel: [
                {
                    label: 'ID',
                    name: 'RawMaterialID',
                    key: true,
                    hidden: true
                },
                {
                    label: 'Name',
                    name: 'RawMaterialName',
                    align: 'left',
                    sortable: true,
                    width: 250,
                    search: true,
                    searchrules: {
                        required: true
                    },
                    searchoptions: {
                        sopt: ["eq", "cn", "bw", "ew"]
                    }
                },
                {
                    label: 'Code',
                    name: 'RawMaterialCode',
                    align: 'left',
                    sortable: true,
                    width: 125,
                    search: true,
                    searchrules: {
                        required: true
                    },
                    searchoptions: {
                        sopt: ["eq", "cn", "bw", "ew"]
                    }
                },
                {
                    label: 'Cost',
                    name: 'RawMaterialUnitCost',
                    align: 'right',
                    sortable: true,
                    width: 75,
                    formatter: 'currency',
                    formatoptions: {
                        decimalSeparator: '.',
                        decimalPlaces: 4,
                        thousandsSeparator: ',',
                        prefix: '£'
                    },
                    search: true,
                    searchrules: {
                        required: true
                    },
                    searchoptions: {
                        sopt: ["eq", "lt", "le", "gt", "ge"]
                    }
                },
                {
                    label: 'Supplier',
                    name: 'RMSupplierName',
                    align: 'left',
                    sortable: true,
                    width: 150,
                    search: true,
                    searchrules: {
                        required: true
                    },
                    searchoptions: {
                        sopt: ["eq", "cn", "bw", "ew"]
                    }
                },
                {
                    label: 'Type',
                    name: 'RMTypeName',
                    align: 'left',
                    sortable: true,
                    width: 175,
                    search: true,
                    searchrules: {
                        required: true
                    },
                    searchoptions: {
                        sopt: ["eq", "cn", "bw", "ew"]
                    }
                },
                {
                    label: 'Last Checked',
                    name: 'DateLastChecked',
                    formatter: 'date',
                    formatoptions: {
                        srcformat: 'Y-m-d',
                        newformat: 'Y M d'
                    },
                    width: 120,
                    sortable: true,
                    align: 'left',
                    search: true,
                    sorttype: "text",
                    searchrules: {
                        custom: true,
                        custom_func: dateCheck
                    },
                    searchoptions: {
                        dataInit: datePick,
                        sopt: ["eq", "lt", "gt"],
                        placeholder: 'yyyy-mm-dd'
                    }
                },
                {
                    label: 'Edit',
                    name: 'EditHTML',
                    align: 'center',
                    title: 'Edit',
                    width: 70,
                    sortable: false,
                    search: false
                },
                {
                    label: 'Delete',
                    name: 'DeleteHTML',
                    align: 'center',
                    width: 70,
                    sortable: false,
                    search: false
                }
            ]
        });
        $("#jqGrid").navGrid('#jqGridPager',
                {
                    search: true,
                    view: false,
                    del: false,
                    edit: false,
                    add: false,
                    view: true
                },
                {}, // edit options
                {}, // add options
                {}, // delete options
                {
                    multipleSearch: true
                }
        );
    });
</script>
<?php echo $this->partial('annie-haak/partial/jqGridJS.phtml'); ?>