<?php

function breadcrumbs() {

    $bc = '<ul class="breadcrumb  hidden-print" xmlns:v="http://rdf.data-vocabulary.org/#">';
    $site = 'http://' . filter_input(INPUT_SERVER, 'HTTP_HOST');
    $crumbs = array_filter(explode("/", filter_input(INPUT_SERVER, 'REQUEST_URI')));
    $count = count($crumbs);
    if ($count == 0) {
        $link = 'Home';
    } else {
        $link = ucwords(str_replace(array(".php", "-", "_"), array("", " ", " "), $crumbs[1]));
    }

    if ($link == 'Home') {
        $bc .= '<li class="active" typeof="v:Breadcrumb"><span class="glyphicon glyphicon-home"></span>&nbsp;&nbsp;Main Menu</li>';
    } else {
        $bc .= '<li typeof="v:Breadcrumb"><a title="Home" href="/home" rel="v:url" property="v:title"><span class="glyphicon glyphicon-home"></span>&nbsp;&nbsp;Main Menu</a></li>';
    }

    if (isset($crumbs[1]) && $crumbs[1] == 'user-admin' && $count > 2) {
        $count = 2;
    } else if ($count > 3) {
        $count = 3;
    }

    for ($i = 1; $i <= $count; $i++) {

        $link = ucwords(str_replace(array(".php", "-", "_"), array("", " ", " "), $crumbs[$i]));

        if ($link != 'Home') {

            $site .= '/' . $crumbs[$i];

            if ($i == $count) {
                $bc .= '<li class=""active typeof="v:Breadcrumb">' . $link . '</li>';
            } else {
                $bc .= '<li typeof="v:Breadcrumb"><a title="' . $link . '" href="' . $site . '" rel="v:url" property="v:title">' . $link . '</a></li>';
            }
        }
    }
    $bc .= '</ul>';

    return $bc;
}

echo breadcrumbs();
