<?php
$topLevel = $this->navigation('navigation')->findAllBy('class', 'top-level');
$crumbs = array_filter(explode("/", filter_input(INPUT_SERVER, 'REQUEST_URI')));
if (count($crumbs) == 0) {
    $crumbs = array('1' => 'home');
}
?>

<nav class="navbar navbar-default " role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">
                <?php echo $this->translate('Edith') ?>
            </a>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-menubuilder">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse navbar-menubuilder">

            <?php
            if ((isset($_SESSION["AnnieHaak"]['storage']['loggedIn']))):
                ?>

                <ul class="nav nav-pills">

                    <?php
                    foreach ($topLevel as $level) {

                        switch ($level->get('route')) {
                            case 'home':
                                $glyphicon = 'glyphicon glyphicon-home';
                                $glyphicon_alt = 'glyphicon glyphicon-home';
                                break;
                            case 'admin-users':
                                $glyphicon = 'glyphicon glyphicon-user';
                                $glyphicon_alt = 'glyphicon glyphicon-user';
                                break;
                            case 'auth/logout':
                                $glyphicon = 'glyphicon glyphicon-off';
                                $glyphicon_alt = 'glyphicon glyphicon-off';
                                break;

                            default:
                                $glyphicon = 'glyphicon glyphicon-folder-open';
                                $glyphicon_alt = 'glyphicon glyphicon-folder-close';
                                break;
                        }

                        if (array_search($level->get('route'), $crumbs)) {
                            echo '<li class="active"><a href="/' . $level->get('route') . '"><span class="' . $glyphicon . '"></span>&nbsp;&nbsp;' . $level->get('label') . '</a></li>';
                        } else {
                            echo '<li class=""><a href="/' . $level->get('route') . '"><span class="' . $glyphicon_alt . '"></span>&nbsp;&nbsp;' . $level->get('label') . '</a></li>';
                        }
                    }
                    ?>


                    <!-- Search -->
                    <!-- ////////////
                                    <form class="navbar-form navbar-left" role="search">
                                      <div class="form-group">
                                        <input class="form-control" placeholder="Search" type="text">
                                      </div>
                                      <button type="submit" class="btn btn-default">Submit</button>
                                    </form>
                    -->

                </ul>
                <!--/ Login/Logout -->

            <?php endif; ?>

        </div>
    </div>
</nav>