
<div class="bs-component pull-right">
    <ul class="pagination">
        <li class="">
            <a href="/business-admin/products/edit/1836">
                <span class="glyphicon glyphicon-step-backward"></span>
            </a>
        </li>
        <li>
            <a href="/business-admin/products/edit/1870">
                <span class="glyphicon glyphicon-backward"></span>
            </a>
        </li>
        <li>
            <a href="/business-admin/products/edit/1871">
                <span class="glyphicon glyphicon-repeat"></span>
            </a>
        </li>
        <li>
            <a href="/business-admin/products/edit/1872">
                <span class="glyphicon glyphicon-forward"></span>
            </a>
        </li>
        <li>
            <a href="/business-admin/products/edit/2603">
                <span class="glyphicon glyphicon-step-forward"></span>
            </a>
        </li>
    </ul>
</div>
<div class="bs-component pagination pull-right">
    <div class="form-group">
        <select class="form-control">
            <option>123123456</option>
            <option>123123456</option>
            <option>123123456</option>
            <option>123123456</option>
            <option>123123456</option>
            <option>123123456</option>
        </select>
    </div>
</div>
<div class="bs-component pagination pull-right">
    <div class="form-group">
        <select class="form-control">
            <option>123123456</option>
            <option>123123456</option>
            <option>123123456</option>
            <option>123123456</option>
            <option>123123456</option>
            <option>123123456</option>
        </select>
    </div>
</div>
<div class="bs-component pagination pull-right">
    <div class="form-group">
        <select class="form-control">
            <option>123123456</option>
            <option>123123456</option>
            <option>123123456</option>
            <option>123123456</option>
            <option>123123456</option>
            <option>123123456</option>
        </select>
    </div>
</div>
