<div class="modal fade" id="buildProductName" tabindex="-1" role="dialog" aria-labelledby="buildProductNameLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="buildProductNameLabel">&nbsp;</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label class="col-md-3 control-label" for="Name">Name:</label>
                    <div class="col-md-9">
                        <?php echo $this->formRow($this->Name); ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" for="NameCharm">Choose Charm:</label>
                    <div class="col-md-9">
                        <?php echo $this->formRow($this->NameCharm); ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" for="NameCrystal">Choose Crystal:</label>
                    <div class="col-md-9">
                        <?php echo $this->formRow($this->NameCrystal); ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" for="NameColour">Choose Colour:</label>
                    <div class="col-md-9">
                        <?php echo $this->formRow($this->NameColour); ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" for="NameLength">Choose Length:</label>
                    <div class="col-md-9">
                        <?php echo $this->formRow($this->NameLength); ?>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="buildProductNameSave" class="btn btn-success" data-dismiss="modal">Done</button>
            </div>
        </div>
    </div>
</div>

<!-- /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// --->

<div class="modal fade" id="imageUlrModal" tabindex="-1" role="dialog" aria-labelledby="currentUlrLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="imageUlrLabel">Current Image</h4>
            </div>
            <div class="modal-body">
                <div class="center-margin">
                    <img src="" id="imageUlrDisplay" class="img-responsive"  />
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<!-- /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// --->

<div class="modal fade" id="feedBackModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-md">
        <div class="modal-content panel-warning">
            <div class="modal-header panel-heading">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" style="color:#000;">There seems to be some issue!</h4>
            </div>
            <div class="modal-body">
                <p id="modalFeedBackMess"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->