<style type="text/css">
    #financialBlock .row {
        border-bottom: 1px dotted #c0c0c0;
    }
    #financialBlock .currSymbol::before{
        content: " £";
    }
    #financialBlock .percSymbol::after{
        content: "%";
    }
    #financialBlock .multi4::after{
        content: " (x4)";
    }
</style>

<div id="financialBlock">

    <div class="row-fluid">
        <div class="col-md-12" id="financialCalcSubTotals">

            <h4>Subtotals:</h4>

            <div class="row">
                <div class="col-md-12">
                    <div class="col-md-3">Raw Material Cost</div>
                    <div class="col-md-2 currSymbol" id="subRawMaterialDsp">00:00</div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="col-md-3">Labour Cost</div>
                    <div class="col-md-2 currSymbol" id="subLabourDsp">00:00</div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="col-md-3">Packing &AMP; Dispatch</div>
                    <div class="col-md-2 currSymbol" id="subDispatchDsp">00:00</div>
                </div>
            </div>

            <div class="row bold text-primary">
                <div class="col-md-12">
                    <div class="col-md-3">Total of Above</div>
                    <div class="col-md-2 currSymbol" id="subTotalsDsp">00:00</div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">&nbsp;</div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="col-md-3">Import &AMP; Charges (<?php echo $ratesPercentages['ImportPercentage']; ?>%)</div>
                    <div class="col-md-2 currSymbol" id="subImportChargesDsp">00:00</div>
                </div>
            </div>

            <div class="row bold text-primary">
                <div class="col-md-12">
                    <div class="col-md-3">Total for Mark Up</div>
                    <div class="col-md-2 currSymbol" id="subMarkUpDsp">00:00</div>
                    <div class="col-md-7 currSymbol multi4" id="subMarkUpX4Dsp">00:00</div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="col-md-3">Box Cost <span id="subBoxCostTxtDsp"></span></div>
                    <div class="col-md-2 currSymbol" id="subBoxCostDsp">00:00</div>
                    <div class="col-md-7 currSymbol multi4" id="subBoxCostX4Dsp">00:00</div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="col-md-3">Bag Cost</div>
                    <div class="col-md-2 currSymbol" id="subBagCostDsp">00:00</div>
                    <div class="col-md-7 currSymbol multi4" id="subBagCostX4Dsp">00:00</div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="col-md-3">Assay Cost</div>
                    <div class="col-md-2 currSymbol" id="subAssayCostDsp">00:00</div>
                    <div class="col-md-7 currSymbol" id="subAssayCostX4Dsp">00:00</div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="col-md-3">Merchant Charge (<?php echo $ratesPercentages['MerchantChargePercentage']; ?>%)</div>
                    <div class="col-md-2 currSymbol" id="subMerchChargeDsp">00:00</div>
                    <div class="col-md-7 currSymbol" id="subMerchChargeX4Dsp">00:00</div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="col-md-3">Postage</div>
                    <div class="col-md-2 currSymbol" id="subPostageDsp">00:00</div>
                    <div class="col-md-7 text-muted">No charge</div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="col-md-3">&nbsp;</div>
                    <div class="col-md-2 text-primary bold currSymbol" id="subTotsAllDsp">00:00</div>
                    <div class="col-md-7 text-primary bold currSymbol" id="subTotsAllX4Dsp">00:00</div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">&nbsp;</div>
            </div>

            <div class="row bold text-primary">
                <div class="col-md-12">
                    <div class="col-md-3">Ex VAT Cost</div>
                    <div class="col-md-2 currSymbol" id="subExVATCostDsp">00:00</div>
                    <div class="col-md-7 currSymbol" id="subExVATCostX4Dsp">00:00</div>
                </div>
            </div>

        </div>
    </div>

    <div class="row-fluid">
        <div class="col-md-12" id="financialCalcRetail">

            <h4>Retail:</h4>

            <div class="row">
                <div class="col-md-3 col-md-offset-8 text-right">Budget without post</div>
                <div class="col-md-1 bold text-primary percSymbol">59.78</div>
            </div>

            <div class="row">
                <div class="col-md-12">&nbsp;</div>
            </div>

            <div class="row">
                <div class="col-md-3 ">RRP Initial</div>
                <div class="col-md-2 currSymbol">
                    <?php echo $this->formRow($form->get('RRP')); ?>
                </div>
                <div class="col-md-2 currSymbol" id="retailRRPLessVATDsp">00:00</div>
                <div class="col-md-2 currSymbol" id="retailCostDsp">00:00</div>
                <div class="col-md-2 currSymbol" id="retailProfitDsp">00:00</div>
                <div class="col-md-1 bold percSymbol" id="retailActualDsp">00</div>
            </div>

            <div class="row">
                <div class="col-md-3 ">Auto add postage in price</div>
                <div class="col-md-2 currSymbol" id="retailPostageProfitDsp">00:00</div>
                <div class="col-md-2">Less VAT</div>
                <div class="col-md-2">Cost</div>
                <div class="col-md-2">Retail Profit</div>
                <div class="col-md-1">Actual</div>
            </div>

            <div class="row">
                <div class="col-md-3  text-primary bold">New RRP</div>
                <div class="col-md-2 currSymbol text-primary bold" id="retailNewRRPDsp">00:00</div>
                <div class="col-md-2 currSymbol" id="retailNewRRPLessVATDsp">00:00</div>
                <div class="col-md-2 currSymbol" id="retailNewCostDsp">00:00</div>
                <div class="col-md-2 currSymbol" id="retailNewProfitDsp">00:00</div>
                <div class="col-md-1 bold text-primary percSymbol" id="retailNewActualDsp">00</div>
            </div>

            <div class="row">
                <div class="col-md-12">&nbsp;</div>
            </div>

            <div class="row">
                <div class="col-md-9"></div>
                <div class="col-md-2 text-right">Target</div>
                <div class="col-md-1 bold text-primary percSymbol">62.00</div>
            </div>

        </div>
    </div>

    <div class="row-fluid">
        <div class="col-md-12" id="financialCalcTrade">

            <h4>Trade:</h4>

            <div class="row">
                <div class="col-md-2">
                    <div class="col-md-12">RRP</div>
                    <div class="col-md-12 currSymbol" id="tradeRRPDsp">00:00</div>
                </div>
                <div class="col-md-2">
                    <div class="col-md-12">Ex VAT</div>
                    <div class="col-md-12 currSymbol" id="tradeExVATDsp">00:00</div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">&nbsp;</div>
            </div>

            <div class="row">
                <div class="col-md-12">60% off:</div>
            </div>

            <div class="row">
                <div class="col-md-2">
                    <div class="col-md-12">Trade Price</div>
                    <div class="col-md-12 currSymbol" id="tradePriceDsp">00:00</div>
                </div>
                <div class="col-md-2">
                    <div class="col-md-12">Cost</div>
                    <div class="col-md-12 currSymbol" id="tradeCostDsp">00:00</div>
                </div>
                <div class="col-md-2">
                    <div class="col-md-12">Sub Total</div>
                    <div class="col-md-12 currSymbol" id="tradeSubTotalDsp">00:00</div>
                </div>
                <div class="col-md-2">
                    <div class="col-md-12">Add Back</div>
                    <div class="col-md-12 currSymbol" id="tradeAddBackDsp">00:00</div>
                </div>
                <div class="col-md-2">
                    <div class="col-md-12">Trade Profit</div>
                    <div class="col-md-12 currSymbol" id="tradeProfitDsp">00:00</div>
                </div>
                <div class="col-md-2">
                    <div class="col-md-12">Actual</div>
                    <div class="col-md-12 bold text-primary percSymbol" id="tradeActualDsp">00:00</div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">&nbsp;</div>
            </div>

            <div class="row">
                <div class="col-md-2">
                    Decimal Places:
                </div>
                <div class="col-md-2">
                    <input type="number" name="cntrlFloatPos" id="cntrlFloatPos" style="width:60%;" min="0" max="10" step="1" />
                </div>
                <div class="col-md-2 col-md-offset-5 text-right">Budget</div>
                <div class="col-md-1 bold text-primary percSymbol">40.00</div>
            </div>

            <div class="row">
                <div class="col-md-12">&nbsp;</div>
            </div>

        </div>
    </div>

</div>
<div class="clearfix margin-bottom-20" id="financialCalcAdjustors"></div>

<?php echo $this->partial('annie-haak/partial/jqGridJS.phtml'); ?>
<script type="application/javascript" src="/js/productsAddEdit.js?v=1"></script>
<script type="application/javascript">
<?php
$temp = 'financialCalcIni(';
$temp .= ($form->getObject()) ? $form->getObject()->RequiresAssay : 0;
$temp .= ',' . $ratesPercentages['AssayRateUnitCost'];
$temp .= ',' . $ratesPercentages['ImportPercentage'];
$temp .= ',' . $ratesPercentages['MerchantChargePercentage'];
$temp .= ',' . $ratesPercentages['PostageCostUnitCost'];
$temp .= ',' . $ratesPercentages['PostageForProfitUnitCost'];
$temp .= ',' . $ratesPercentages['VATPercentage'];
$temp .= ');';
echo $temp;
?>
</script>