<?php

return array(
    'guest' => array(
        'Auth/login',
        'Auth/logout',
        'Auth/process',
        'Auth/authenticate',
        'Success/index',
        'Index/index',
        'BusinessAdmin/index',
        'Collections/index',
        'LabourItems/index',
        'Packaging/index',
        'Products/index',
        'ProductTypes/index',
        'RatesPercentages/index',
        'RawMaterials/index',
        'RawMaterialTypes/index',
        'Suppliers/index',
        'Reports/index',
        'Users/index',
    ),
    'standard' => array(
        'Collections/add',
        'Collections/edit',
        'Collections/delete',
        'LabourItems/add',
        'LabourItems/edit',
        'LabourItems/delete',
        'Packaging/add',
        'Packaging/edit',
        'Packaging/delete',
        'Products/add',
        'Products/edit',
        'Products/delete',
        'ProductTypes/add',
        'ProductTypes/edit',
        'ProductTypes/delete',
        'RatesPercentages/edit',
        'RawMaterials/add',
        'RawMaterials/edit',
        'RawMaterials/delete',
        'RawMaterialTypes/add',
        'RawMaterialTypes/edit',
        'RawMaterialTypes/delete',
        'Suppliers/add',
        'Suppliers/edit',
        'Suppliers/delete',
    ),
    'admin' => array(
    ),
);
