<div class="page-header">
    <h1>Create and Add</h1>
</div>
<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">Choose a sub-action:</h3>
    </div>
    <div class="panel-body">
        <div class="col-lg-3 col-md-3 col-sm-4">
            <div class="list-group table-of-contents">
                <a class="list-group-item" href="/reports/collection">Collection</a>
                <a class="list-group-item" href="/reports/labour-time">Labour Time</a>
                <a class="list-group-item" href="/reports/packaging">Packaging</a>
                <a class="list-group-item" href="/reports/product">Product</a>
                <a class="list-group-item" href="/reports/product-type">Product Type</a>
                <a class="list-group-item" href="/reports/raw-material">Raw Material</a>
                <a class="list-group-item" href="/reports/raw-material-type">Raw Material Type</a>
                <a class="list-group-item" href="/reports/supplier">Supplier</a>
            </div>
        </div>
    </div>
</div>