<?php

dump($finDataJSON);
#dump($products);

foreach ($products as $product) {
    echo '<div>';
    echo '<a href="/run-financial-calcs/' . $product->ProductID . '">Update Financials</a>';
    echo ' || <a target="_blank" href="/business-admin/products/print/' . $product->ProductID . '">Print View</a>';
    echo '<p>' . $product->ProductID . ' - ' . $product->ProductName . '</p>';
    dump($product->FinancialDataJSON);
    echo '</div>';
}
?>
