<?php
$title = 'Delete Product Type';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($productTypes->ProductTypeName); ?>'?
</p>
<?php
$url = $this->url('$productTypes', array(
    'action' => 'delete',
    'id' => $this->id,
        ));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $productTypes->ProductTypeId; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>

