<?php
$title = 'Product Types';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('productTypes', array('action' => 'add')); ?>">Add new product type</a>
</p>

<table class="table">
    <tr>
        <th>Product Name</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($productTypes as $productType) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($productType->ProductTypeName); ?></td>
            <td>
                <a href="<?php echo $this->url('productTypes', array('action' => 'edit', 'id' => $productType->ProductTypeId));
        ?>">Edit</a>
                <a href="<?php echo $this->url('productTypes', array('action' => 'delete', 'id' => $productType->ProductTypeId));
        ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
