<div class="page-header">
    <h1>View &amp; Edit</h1>
</div>
<p>Choose a sub-action.</p>
<div class="col-lg-3 col-md-3 col-sm-4">
    <div class="list-group table-of-contents">
        <a class="list-group-item" href="/view-edit/collections">Collections</a>
        <a class="list-group-item" href="/view-edit/labour-time">Labour Time</a>
        <a class="list-group-item" href="/view-edit/packaging">Packaging</a>
        <a class="list-group-item" href="/view-edit/products">Products</a>
        <a class="list-group-item" href="/view-edit/product-types">Product Types</a>
        <a class="list-group-item" href="/view-edit/rates-percentages">Rates &amp; Percentages</a>
        <a class="list-group-item" href="/view-edit/rawMaterials">Raw Materials</a>
        <a class="list-group-item" href="/view-edit/rawMaterial-types">Raw Material Types</a>
        <a class="list-group-item" href="/view-edit/suppliers">Suppliers</a>
    </div>
</div>