<div class="page-header">
    <h1>Main Menu</h1>
</div>
<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">Choose a main action to perform:</h3>
    </div>
    <div class="panel-body">
        <div class="">
            <div class="list-group ">
                <a class="list-group-item" href="/admin-users">Admin Users</a>
                <a class="list-group-item" href="/create-add">Create &amp; Add</a>
                <a class="list-group-item" href="/reports">Produce Reports</a>
                <a class="list-group-item" href="/view-edit">View &amp; Edit</a>        
            </div>
        </div>
    </div>
</div>