<?php
$topLevel = $this->navigation('navigation')->toArray();
echo $this->UIPageTitleFormatter($this->navigation('navigation')->findActive('navigation')['page']->label);
?>

<div class="col-lg-6">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">Choose a main action to perform:</h3>
        </div>
        <div class="panel-body">
            <div class="">
                <div class="list-group ">
                    <?php
                    for ($idx = 0; $idx < count($topLevel); $idx++) {

                        switch ($topLevel[$idx]['route']) {
                            case 'home':
                                $glyphicon = 'glyphicon glyphicon-home';
                                $glyphicon_alt = 'glyphicon glyphicon-home';
                                break;
                            case 'user-admin':
                                $glyphicon = 'glyphicon glyphicon-user';
                                $glyphicon_alt = 'glyphicon glyphicon-user';
                                break;
                            case 'auth/logout':
                                $glyphicon = 'glyphicon glyphicon-off';
                                $glyphicon_alt = 'glyphicon glyphicon-off';
                                break;

                            default:
                                $glyphicon = 'glyphicon glyphicon-folder-open';
                                $glyphicon_alt = 'glyphicon glyphicon-folder-close';
                                break;
                        }

                        echo '<a class="list-group-item" href="/' . $topLevel[$idx]['route'] . '"><span class="' . $glyphicon_alt . '"></span>&nbsp;&nbsp;' . $topLevel[$idx]['label'] . '</a>';
                    }
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>