<div class="page-header">
    <h1>Home Page</h1>
</div>
<p>Choose an action.</p>
<div class="col-lg-3 col-md-3 col-sm-4">
    <div class="list-group table-of-contents">
        <a class="list-group-item" href="/view-edit">View &amp; Edit</a>
        <a class="list-group-item" href="/reports">Produce Reports</a>
        <a class="list-group-item" href="/create-add">Create &amp; Add</a>
    </div>
</div>