<?php

echo $this->UIPageTitleFormatter($this->navigation('navigation')->findActive('navigation')['page']->label);

$form->setAttribute('action', $this->url('business-admin/packaging', array('action' => 'add')));
$form->setAttributes(array('class' => 'form-horizontal'));
$form->prepare();

echo '<div class="well bs-component">';

echo $this->form()->openTag($form);

echo '<fieldset><legend>Add Packaging</legend>';

echo $this->formHidden($form->get('PackagingID')->setValue(0));

echo '<div class="form-group">';
echo '<label class="col-lg-2 control-label" for="PackagingName">Packaging Name:</label><div class="col-lg-10">';
echo $this->formRow($form->get('PackagingName'));
echo '</div></div>';

echo '<div class="form-group">';
echo '<label class="col-lg-2 control-label" for="PackagingCode">Packaging Code:</label><div class="col-lg-10">';
echo $this->formRow($form->get('PackagingCode'));
echo '</div></div>';

echo '<div class="form-group">';
echo '<label class="col-lg-2 control-label" for="PackagingUnitCost">Packaging Unit Cost:</label><div class="col-lg-10">';
echo $this->formRow($form->get('PackagingUnitCost'));
echo '</div></div>';

echo '<div class="form-group">';
echo '<label class="col-lg-2 control-label" for="PackagingType">Packaging Type:</label><div class="col-lg-10">';
echo $this->formRow($form->get('PackagingType'));
echo '</div></div>';

echo '<div class="form-group">';
echo '<div class="col-lg-10 col-lg-offset-2">';
echo '<a href="/business-admin/packaging" type="reset" class="btn btn-default btn-sm margin-right-10">Cancel</a>';
$form->get('submit')->setAttribute('class', 'btn btn-success btn-sm');
echo $this->formSubmit($form->get('submit'));
echo '</div></div>';

echo '</fieldset>';

echo $this->form()->closeTag();

echo '</div>';

dump($form);
