<?php
$url = $this->url('business-admin/packaging', array('action' => 'delete', 'id' => $this->id,));

echo $this->UIPageTitleFormatter($this->navigation('navigation')->findActive('navigation')['page']->label);
?>

<div class="well bs-component">
    <form action="<?php echo $url; ?>" method="post">

        <fieldset>
            <legend>Delete Packaging?</legend>

            <div class="form-group">
                <div class="col-md-10">
                    <div class="panel panel-warning">
                        <div class="panel-heading">
                            <h3 class="panel-title">Warning!</h3>
                        </div>
                        <div class="panel-body">
                            Are you sure that you want to delete <span class="text-warning bold">"<?php echo $this->escapeHtml($packaging->PackagingName); ?>"</span>?
                        </div>
                    </div>
                </div>
            </div>

            <input type="hidden" name="id" value="<?php echo (int) $packaging->PackagingID; ?>" />
            <div class="form-group">
                <div class="col-md-3 col-md-offset-7">
                    <a href="/business-admin/packaging" type="reset" class="btn btn-default">Cancel</a>
                    <button type="submit" class="btn btn-danger" name="del" value="Yes">Delete</button>
                </div>
            </div>
        </fieldset>

    </form>

</div>