<?php
echo $this->UIPageTitleFormatter($this->navigation('navigation')->findActive('navigation')['page']->label);

$form = $this->form;
$form->setAttribute('action', $this->url('business-admin/packaging', array('action' => 'edit', 'id' => $this->id,)));
$form->setAttributes(array('class' => 'form-horizontal'));
$form->prepare();
?>

<div class="well bs-component">

    <?php echo $this->form()->openTag($form); ?>

    <fieldset>
        <legend>Edit Packaging</legend>

        <?php echo $this->formHidden($form->get('PackagingID')); ?>

        <div class="form-group">
            <label class="col-md-2 control-label" for="PackagingName">Packaging Name:</label>
            <div class="col-md-10">
                <?php echo $this->formRow($form->get('PackagingName')); ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label" for="PackagingCode">Packaging Code:</label>
            <div class="col-md-10">
                <?php echo $this->formRow($form->get('PackagingCode')); ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label" for="PackagingUnitCost">Packaging Unit Cost:</label>
            <div class="col-md-10">
                <div class="input-group">
                    <div class="input-group-addon">£</div>
                    <?php echo $this->formRow($form->get('PackagingUnitCost')); ?>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label" for="PackagingType">Packaging Type:</label>
            <div class="col-md-10">
                <?php echo $this->formRow($form->get('PackagingType')); ?>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-3 col-md-offset-9">
                <a href="/business-admin/packaging" type="reset" class="btn btn-default margin-right-10">Cancel</a>
                <?php echo $this->formSubmit($form->get('submit')); ?>
            </div></div>

    </fieldset>

    <?php echo $this->form()->closeTag(); ?>

</div>