<?php
$form = $this->form;

echo $this->UIPageTitleFormatter($this->navigation('navigation')->findActive('navigation')['page']->label);

$form->setAttribute('action', $this->url('business-admin/rates-percentages', array('action' => 'edit')));
$form->setAttributes(array('class' => 'form-horizontal'));
$form->get('submit')->setAttribute('value', 'Update');
$form->prepare();
?>

<div class="well bs-component">

    <?php echo $this->form()->openTag($form); ?>

    <div class="form-group">
        <label class="col-md-2 control-label" for="AssayRateUnitCost">Assay Cost &pound;:</label>
        <div class="col-md-10">
            <?php echo $this->formRow($form->get('AssayRateUnitCost')); ?>
        </div>
    </div>

    <div class="form-group">
        <label class="col-md-2 control-label" for="ImportPercentage">Import Rate &#37;:</label>
        <div class="col-md-10">
            <?php echo $this->formRow($form->get('ImportPercentage')); ?>
        </div>
    </div>

    <div class="form-group">
        <label class="col-md-2 control-label" for="MerchantChargePercentage">Merchant Charge &#37;:</label>
        <div class="col-md-10">
            <?php echo $this->formRow($form->get('MerchantChargePercentage')); ?>
        </div>
    </div>

    <div class="form-group">
        <label class="col-md-2 control-label" for="PackageAndDispatchUnitCost">Package and Dispatch Cost &pound;:</label>
        <div class="col-md-10">
            <?php echo $this->formRow($form->get('PackageAndDispatchUnitCost')); ?>
        </div>
    </div>

    <div class="form-group">
        <label class="col-md-2 control-label" for="PostageCostUnitCost">Post Cost &pound;:</label>
        <div class="col-md-10">
            <?php echo $this->formRow($form->get('PostageCostUnitCost')); ?>
        </div>
    </div>

    <div class="form-group">
        <label class="col-md-2 control-label" for="PostageForProfitUnitCost">Post for Profit Cost &pound;:</label>
        <div class="col-md-10">
            <?php echo $this->formRow($form->get('PostageForProfitUnitCost')); ?>
        </div>
    </div>

    <div class="form-group">
        <label class="col-md-2 control-label" for="VATPercentage">VAT Rate &pound;:</label>
        <div class="col-md-10">
            <?php echo $this->formRow($form->get('VATPercentage')); ?>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-3 col-md-offset-9">
            <a href="/business-admin/rates-percentages" type="reset" class="btn btn-default">Cancel</a>
            <?php echo $this->formSubmit($form->get('submit')); ?>
        </div>
    </div>

</fieldset>

<?php echo $this->form()->closeTag(); ?>

</div>
