<?php
echo $this->UIPageTitleFormatter($this->navigation('navigation')->findActive('navigation')['page']->label);
echo '<p class="pull-right">' . $this->UIAccessControlButtons($_SESSION['AnnieHaak']['storage']['userInfo']['roleLevel'], 'edit', '/business-admin/rates-percentages/edit', 'Edit') . '</p>';
?>

<a href="/business-admin/rates-percentages" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-refresh"></span> Refresh Page</a>

<table class="table table-striped table-responsive table-hover ">
    <thead>
        <tr class="text-info">
            <th>Name</th>
            <th>Value</th>
        </tr>
    </thead>
    <tbody>
        <?php
        echo '<tr><td>Assay Cost</td><td>£' . number_format($ratesPercentages->AssayRateUnitCost, 4) . '</td></tr>';
        echo '<tr><td>Import Rate</td><td>' . number_format($ratesPercentages->ImportPercentage, 2) . ' %</td></tr>';
        echo '<tr><td>Merchant Charge</td><td>' . number_format($ratesPercentages->MerchantChargePercentage, 2) . ' %</td></tr>';
        echo '<tr><td>Packaging and Dispatch Cost</td><td>£' . number_format($ratesPercentages->PackageAndDispatchUnitCost, 4) . '</td></tr>';
        echo '<tr><td>Post Cost</td><td>£' . number_format($ratesPercentages->PostageCostUnitCost, 4) . '</td></tr>';
        echo '<tr><td>Post For Profit Cost</td><td>£' . number_format($ratesPercentages->PostageForProfitUnitCost, 4) . '</td></tr>';
        echo '<tr><td>VAT Rate</td><td>' . number_format($ratesPercentages->VATPercentage, 2) . ' %</td></tr>';
        ?>
    </tbody>
</table>
