<?php
echo $this->UIPageTitleFormatter($this->navigation('navigation')->findActive('navigation')['page']->label);
echo '<p class="pull-right">' . $this->UIAccessControlButtons($_SESSION['AnnieHaak']['storage']['userInfo']['roleLevel'], 'edit', '/business-admin/rates-percentages/edit', 'Edit') . '</p>';
echo $this->partial('annie-haak/partial/reloadButton.phtml');
?>

<table class="table table-striped table-responsive table-hover ">
    <thead>
        <tr class="text-info">
            <th>Name</th>
            <th>Value</th>
        </tr>
    </thead>
    <tbody>
        <?php
        echo '<tr><td class="bold">Assay Cost</td><td>£' . number_format($ratesPercentages->AssayRateUnitCost, 4) . '</td></tr>';
        echo '<tr><td class="bold">Import Rate</td><td>' . number_format($ratesPercentages->ImportPercentage, 2) . ' %</td></tr>';
        echo '<tr><td class="bold">Merchant Charge</td><td>' . number_format($ratesPercentages->MerchantChargePercentage, 2) . ' %</td></tr>';
        echo '<tr><td class="bold">Packaging and Dispatch Cost</td><td>£' . number_format($ratesPercentages->PackageAndDispatchUnitCost, 4) . '</td></tr>';
        echo '<tr><td class="bold">Post Cost</td><td>£' . number_format($ratesPercentages->PostageCostUnitCost, 4) . '</td></tr>';
        echo '<tr><td class="bold">Post For Profit Cost</td><td>£' . number_format($ratesPercentages->PostageForProfitUnitCost, 4) . '</td></tr>';
        echo '<tr><td class="bold">VAT Rate</td><td>' . number_format($ratesPercentages->VATPercentage, 2) . ' %</td></tr>';
        ?>
    </tbody>
</table>
