<?php
echo $this->UIPageTitleFormatter($this->navigation('navigation')->findActive('navigation')['page']->label);
/*
  dump($collectionsTypesReport->reportDataArr);
  $collection['ProductCollectionName'];
  $collection['ProductTypeName'];
  $collection['ProductCount'];

 */
?>
<div class="col-lg-4">
    <div class="bs-component">

        <?php
        foreach ($collectionsTypesReport->reportDataArr[0] as $key => $value) {

            echo '<table class="table table-striped table-hover">';
            echo '<thead><tr><th class="bg-primary" colspan="2">' . $key . '</th></tr></thead>';
            echo '<tbody>';

            foreach ($value as $item) {
                echo '<tr>';
                echo '<td style="width:250px;">' . $item[0] . '</td>';
                echo '<td>' . $item[1] . '</td>';
                echo '</tr>';
            }

            echo '</tbody></table>';
        }
        echo '<p>' . date('l jS F Y, G:i:s', time()) . '</p>';
        ?>

    </div>
</div>
