<?php

echo $this->UIPageTitleFormatter($this->navigation('navigation')->findActive('navigation')['page']->label);

$count = 1;
echo '<div class="col-md-12">';
echo '<div class="row">';

foreach ($collectionsTypesReport as $key => $value) {

    echo '<div class="col-md-6"><table class="table table-bordered">';
    echo '<thead><tr><th class="" colspan="2">' . $key . '</th></tr></thead>';
    echo '<tbody>';
    foreach ($value as $item) {
        echo '<tr>';
        echo '<td style="width:250px;">' . $item[0] . '</td>';
        echo '<td>' . $item[1] . '</td>';
        echo '</tr>';
    }
    echo '</tbody></table></div>';

    if ($count == 2) {
        echo '</div><p>&nbsp;</p><div class="row">';
        $count = 0;
    }
    $count++;
}

echo '</div></div>';
echo '<p>' . date('l jS F Y, G:i:s', time()) . '</p>';
