<div class="col-lg-10">
    <div class="page-header">
        <h1>Reports</h1>
    </div>
</div>
<div class="col-lg-6">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">Choose a sub-action:</h3>
        </div>
        <div class="panel-body">
            <div class="list-group table-of-contents">
                <a class="list-group-item" href="/reports/dynamic-reports">All Dynamic Report</a>
                <a class="list-group-item" href="/reports/collections-occasions">Collections &amp; Occasions</a>
                <a class="list-group-item" href="/reports/margins">Margins</a>
                <a class="list-group-item" href="/reports/products-by-occasions">Products By Occasions</a>
                <a class="list-group-item" href="/reports/rrp-rms">RRP &amp; RMs</a>
                <a class="list-group-item" href="/reports/trade-pack-rms-time">Trade Pack RMs + Time</a>
            </div>
        </div>
    </div>
</div>