<?php
echo $this->UIPageTitleFormatter($this->navigation('navigation')->findActive('navigation')['page']->label);

#dump($marginsReport);
#exit();
?>
<div class = "col-lg-12">
    <div class = "bs-component">
        <table class="table table-striped table-hover">
            <thead>
                <tr class="bg-primary">
                    <th>SKU</th>
                    <th>Name</th>
                    <th>Type</th>
                    <th>Collection</th>
                    <th>Current</th>
                    <th>Trade Pack</th>
                    <th>RRP</th>
                    <th>Retail Profit</th>
                    <th>Retail Margin</th>
                    <th>Trade Profit</th>
                    <th>Trade Margin</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($marginsReport->reportDataArr as $value) {
                    echo '<tr>';
                    echo '<td>' . $value['SKU'] . '</td>';
                    echo '<td>' . $value['Name'] . '</td>';
                    echo '<td>' . $value['Type'] . '</td>';
                    echo '<td>' . $value['Collection'] . '</td>';
                    echo '<td>' . $value['Current'] . '</td>';
                    echo '<td>' . $value['TradePack'] . '</td>';
                    echo '<td>' . $this->UICurrencyFormatter($value['RRP'], TRUE) . '</td>';
                    echo '<td>' . $this->UICurrencyFormatter($value['RetailProfit'], TRUE) . '</td>';
                    echo '<td>' . round($value['RetailMargin'], 2) . '%</td>';
                    echo '<td>' . $this->UICurrencyFormatter($value['TradeProfit'], TRUE) . '</td>';
                    echo '<td>' . round($value['TradeMargin'], 2) . '%</td></tr>';
                    echo '</tr>';
                }
                ?>
            </tbody>
        </table>
        <?php
        echo '<p>' . date('l jS F Y, G:i:s', time()) . '</p>';
        ?>
    </div>
</div>