<?php
echo $this->UIPageTitleFormatter($this->navigation('navigation')->findActive('navigation')['page']->label);


/* dump($marginsReport);
 * SKU
 * Name
 * Type
 * Collection
 * Current
 * Trade Pack
 * RRP = [RRP] + (DLookUp("PostageForProfitUnitCost", "PostageForProfitLookup"))
 * Retail Profit = [RRP + Postage - Vat]-[ExVatCost]
 * Retail Margin = [Retail Profit]/[RRP + Postage - Vat]
 * Trade Profit = IIf([ExcludeFromTrade] = -1, 'N/A', [tradeprofsub] + [addback])
 * Trade Margin = IIf([ExcludeFromTrade] = -1, 'N/A', [Trade Profit] / [TradePrice])
 */
?>
<div class = "col-lg-12">
    <div class = "bs-component">
        <table class="table table-striped table-hover">
            <thead>
                <tr class="bg-primary">
                    <th>SKU</th>
                    <th>Name</th>
                    <th>Type</th>
                    <th>Collection</th>
                    <th>Current</th>
                    <th>Trade Pack</th>
                    <th>RRP</th>
                    <th>Retail Profit</th>
                    <th>Retail Margin</th>
                    <th>Trade Profit</th>
                    <th>Trade Margin</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($marginsReport->reportDataArr as $value) {
                    echo '<tr>';
                    echo '<td>' . $value['SKU'] . '</td>';
                    echo '<td>' . $value['Name'] . '</td>';
                    echo '<td>' . $value['Type'] . '</td>';
                    echo '<td>' . $value['Collection'] . '</td>';
                    echo '<td>' . (($value['Current']) ? 'Yes' : 'No') . '</td>';
                    echo '<td>' . (($value['TradePack']) ? 'Yes' : 'No') . '</td>';
                    echo '<td>' . $this->UICurrencyFormatter($value['RRP'], TRUE) . '</td>';
                    #echo '<td>' . $value['RetailProfit'] . '</td>';
                    #echo '<td>' . $value['RetailMargin'] . '</td>';
                    #echo '<td>' . $value['TradeProfit'] . '</td>';
                    #echo '<td>' . $value['TradeMargin'] . '</td></tr>';
                    echo '<td></td>';
                    echo '<td></td>';
                    echo '<td></td>';
                    echo '<td></td>';
                    echo '</tr>';
                }
                ?>
            </tbody>
        </table>
        <?php
        echo '<p>' . date('l jS F Y, G:i:s', time()) . '</p>';
        ?>
    </div>
</div>