<?php
echo $this->UIPageTitleFormatter($this->navigation('navigation')->findActive('navigation')['page']->label);

$form->setAttribute('action', $this->url('business-admin/product-types', array('action' => 'add')));
$form->setAttributes(array('class' => 'form-horizontal'));

$form->prepare();
?>

<div class="well bs-component">

    <?php echo $this->form()->openTag($form); ?>

    <fieldset>

        <?php echo $this->formHidden($form->get('ProductTypeId')); ?>

        <div class="form-group">
            <label class="col-md-2 control-label" for="ProductTypeName">Product Type Name:</label>
            <div class="col-md-10">
                <?php echo $this->formRow($form->get('ProductTypeName')); ?>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-3 col-md-offset-9">
                <a href="/business-admin/product-types" type="reset" class="btn btn-default">Cancel</a>
                <?php echo $this->formSubmit($form->get('submit')); ?>
            </div>
        </div>

    </fieldset>

    <?php echo $this->form()->closeTag(); ?>

</div>
