<?php

    $url = $this->url('view-edit/product-types', array('action' => 'delete', 'id' => $this->id,));
?>

<div class="well bs-component">

    <form action="<?php echo $url; ?>" method="post">

        <fieldset>
            <legend>Delete Product Type</legend>
            
            <div class="form-group">
                <div class="col-lg-10">
                    <div class="panel panel-warning">
                        <div class="panel-heading">
                            <h3 class="panel-title">Warning</h3>
                        </div>
                        <div class="panel-body">
                            Are you sure that you want to delete '<?php echo $this->escapeHtml($productTypes->ProductTypeName); ?>'?
                        </div>
                    </div>
                </div>
            </div>
            
            <input type="hidden" name="id" value="<?php echo (int) $productTypes->ProductTypeId; ?>" />
            <div class="form-group">
                <div class="col-lg-10 col-lg-offset-1">
                    <button type="submit" class="btn btn-default" name="del" value="No">Cancel</button>
                    <button type="submit" class="btn btn-danger" name="del" value="Yes">Delete</button>
                </div>
            </div>
        </fieldset>

    </form>
    
</div>
