<?php
$title = 'Product Types';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('productTypes', array('action' => 'add')); ?>">Add new product type</a>
</p>

<table class="table table-striped table-hover ">
    <thead>
        <tr>
            <th>Product Name</th>
            <th colspan="2">Actions</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($productTypes as $productType) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($productType->ProductTypeName); ?></td>
            <td>
                <a href="<?php echo $this->url('productTypes', array('action' => 'edit', 'id' => $productType->ProductTypeId));
        ?>">Edit</a>
            </td>
            <td>
                <a href="<?php echo $this->url('productTypes', array('action' => 'delete', 'id' => $productType->ProductTypeId));
        ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
