<?php
echo $this->UIPageTitleFormatter($this->navigation('navigation')->findActive('navigation')['page']->label);
echo $this->UIAccessControlButtons($_SESSION['AnnieHaak']['storage']['userInfo']['roleLevel'], 'add', '/business-admin/product-types/add', 'Add new Product Type');
echo $this->partial('annie-haak/partial/reloadButton.phtml');
?>

<table class="table table-striped table-responsive table-hover ">
    <thead>
        <tr class="text-info">
            <th>Product Name</th>
            <th colspan="2" style="width: 25%;">Actions</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($productTypes as $productType) : ?>
            <tr>
                <td class="bold">
                    <?php echo $this->escapeHtml($productType->ProductTypeName); ?>
                </td>
                <td>
                    <?php echo $this->UIAccessControlButtons($_SESSION['AnnieHaak']['storage']['userInfo']['roleLevel'], 'edit', '/business-admin/product-types/edit/' . $productType->ProductTypeId, 'Edit'); ?>
                </td>
                <td>
                    <?php echo $this->UIAccessControlButtons($_SESSION['AnnieHaak']['storage']['userInfo']['roleLevel'], 'delete', '/business-admin/product-types/delete/' . $productType->ProductTypeId, 'Delete'); ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>