<?php
echo $this->UIPageTitleFormatter($this->navigation('navigation')->findActive('navigation')['page']->label);

$form->setAttribute('action', $this->url('business-admin/collections', array('action' => 'add')));
$form->setAttributes(array('class' => 'form-horizontal'));
$form->prepare();
?>

<div class="well bs-component">

    <?php echo $this->form()->openTag($form); ?>

    <fieldset>
        <legend>Add Collection</legend>

        <?php echo $this->formHidden($form->get('ProductCollectionID')->setValue(0)); ?>

        <div class="form-group">
            <label class="col-lg-2 control-label" for="ProductTypeName">Collection Name:</label>
            <div class="col-lg-10">
                <?php echo $this->formRow($form->get('ProductCollectionName')); ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-lg-2 control-label" for="ProductCollectionCode">Collection Code:</label>
            <div class="col-lg-10">
                <?php echo $this->formRow($form->get('ProductCollectionCode')); ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-lg-2 control-label" for="Current">Current:</label>
            <div class="col-lg-10">
                <?php echo $this->formRow($form->get('Current')); ?>
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-3 col-lg-offset-9">
                <a href="/business-admin/collections" type="reset" class="btn btn-default btn-info-outline margin-right-10">Cancel</a>
                <?php echo $this->formSubmit($form->get('submit')); ?>
            </div>
        </div>

    </fieldset>

    <?php echo $this->form()->closeTag(); ?>

</div>
