<div class="col-lg-10">

    <div class="page-header">
        <h1>Collections</h1>
    </div>

    <?php
    $url = $this->url('business-admin/collections', array('action' => 'delete', 'id' => $this->id,));
    ?>

    <div class="well bs-component">
        <form action="<?php echo $url; ?>" method="post">

            <fieldset>
                <legend>Delete Collection</legend>

                <div class="form-group">
                    <div class="col-lg-10">
                        <div class="panel panel-warning">
                            <div class="panel-heading">
                                <h3 class="panel-title">Warning</h3>
                            </div>
                            <div class="panel-body">
                                Are you sure that you want to delete <span class="text-warning lead">"<?php echo $this->escapeHtml($collections->ProductCollectionName); ?>"</span> ?
                            </div>
                        </div>
                    </div>
                </div>

                <input type="hidden" name="id" value="<?php echo (int) $collections->ProductCollectionID; ?>" />
                <div class="form-group">
                    <div class="col-lg-10 col-lg-offset-1">
                        <button type="submit" class="btn btn-default" name="del" value="No">Cancel</button>
                        <button type="submit" class="btn btn-danger" name="del" value="Yes">Delete</button>
                    </div>
                </div>
            </fieldset>

        </form>
    </div>

</div>