<?php
echo $this->UIPageTitleFormatter($this->navigation('navigation')->findActive('navigation')['page']->label);
echo $this->UIAccessControlButtons($_SESSION['AnnieHaak']['storage']['userInfo']['roleLevel'], 'add', '/business-admin/collections/add', 'Add new Collection');
echo $this->partial('annie-haak/partial/reloadButton.phtml');
?>

<table class="table table-striped table-hover ">
    <thead>
        <tr class="text-info">
            <th>Collection Name</th>
            <th>Current</th>
            <th colspan="2" style="width: 25%;">Actions</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($collections as $collection) : ?>
            <tr>
                <td>
                    <?php echo $this->escapeHtml($collection->ProductCollectionName); ?>
                </td>
                <td>
                    <?php echo ($this->escapeHtml($collection->Current)) ? '<span class="glyphicon glyphicon-ok"></span>' : '<span class="glyphicon glyphicon-remove"></span>'; ?>
                </td>
                <td>
                    <?php echo $this->UIAccessControlButtons($_SESSION['AnnieHaak']['storage']['userInfo']['roleLevel'], 'edit', '/business-admin/collections/edit/' . $collection->ProductCollectionID, 'Edit'); ?>
                </td>
                <td>
                    <?php echo $this->UIAccessControlButtons($_SESSION['AnnieHaak']['storage']['userInfo']['roleLevel'], 'delete', '/business-admin/collections/delete/' . $collection->ProductCollectionID, 'Delete'); ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
