<div class="col-lg-10">

    <div class="page-header">
        <h1>Collections</h1>
    </div>

    <a class="btn btn-success" href="<?php echo $this->url('business-admin/collections', array('action' => 'add')); ?>">
        <span class="glyphicon glyphicon-plus"></span>&nbsp;&nbsp;Add a new Collection
    </a>

    <table class="table table-striped table-hover ">
        <thead>
            <tr>
                <th>Collection Name</th>
                <th colspan="2">Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($collections as $collection) : ?>
                <tr>
                    <td>
                        <h5>
                            <?php echo $this->escapeHtml($collection->ProductCollectionName); ?>
                        </h5>
                    </td>
                    <td>
                        <a class="btn btn-warning" href="<?php echo $this->url('business-admin/collections', array('action' => 'edit', 'id' => $collection->ProductCollectionID));
                            ?>"><span class="glyphicon glyphicon-pencil"></span>&nbsp;&nbsp;Edit</a>
                    </td>
                    <td>
                        <a class="btn btn-danger" href="<?php echo $this->url('business-admin/collections', array('action' => 'delete', 'id' => $collection->ProductCollectionID));
                            ?>"><span class="glyphicon glyphicon-trash"></span>&nbsp;&nbsp;Delete</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

</div>