<?php

use Zend\Form\Element;
use Zend\Captcha\Image as CaptchaImage;

$form = $this->form;

$csrf = new Element\Csrf('security');
$form->add(array(
    'type' => 'Zend\Form\Element\Csrf',
    'name' => 'security',
    'options' => array(
        'csrf_options' => array(
            'timeout' => 600
        )
    )
        )
);

$form->setAttributes(array(
    'class' => 'form-horizontal'
        )
);
$form->setAttribute('action', $this->url(
                'login/process', array(
            'action' => 'authenticate',
                )
        )
);


$captchaImage = new CaptchaImage(array(
    'font' => getcwd() . '/data/captcha/fonts/arial.ttf',
    'width' => 250,
    'height' => 100,
    'dotNoiseLevel' => 40,
    'lineNoiseLevel' => 3)
);
$captchaImage->setImgDir(getcwd() . '/public/img/captcha');
$captchaImage->setImgUrl('/img/captcha');

//add captcha element...
$form->add(array(
    'type' => 'Zend\Form\Element\Captcha',
    'name' => 'captcha',
    'attributes' => array(
        'id' => 'captcha',
        'class' => 'form-control',
        'placeholder' => 'Please enter the above characters',
        'required' => TRUE,
    ),
    'options' => array(
        'captcha' => $captchaImage,
    ),
));

$form->prepare();
?>

<div class="col-lg-9">
    <div class="bs-component well">

        <?php echo $this->form()->openTag($form); ?>

        <fieldset>
            <legend>Login</legend>

            <div class="form-group">
                <label class="col-lg-3 control-label" for="username">Username:</label>
                <div class="input-group">
                    <span class="input-group-addon">@</span>
                    <?php echo $this->formRow($form->get('username')); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-3 control-label" for="password">Password:</label>
                <div class="input-group">
                    <span class="input-group-addon glyphicon glyphicon-lock"></span>
                    <?php echo $this->formRow($form->get('password')); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-3 control-label" for="captcha">Are you human?</label>
                <div class="col-lg-9">
                    <?php echo $this->formRow($form->get('captcha')); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-3 control-label" for="rememberme">Remember device?</label>
                <div class="col-lg-9">
                    <?php echo $this->formRow($form->get('rememberme')); ?>
                    <button
                        title=""
                        data-original-title=""
                        type="button"
                        class="btn btn-info margin-left-10"
                        data-container="body"
                        data-toggle="popover"
                        data-placement="top"
                        data-content="Enabling this will keep you logged in on this device until you deliberately log out. Do not enable this on public devices!">
                        What does this mean?
                    </button>
                </div>
            </div>

            <?php echo $this->formRow($form->get('security')); ?>

            <div class="form-group">
                <div class="col-lg-offset-3 col-lg-9">
                    <button class="btn btn-default" type="reset" value="Reset"><span class='glyphicon glyphicon-refresh'></span> Clear</button>
                    <?php echo $this->formSubmit($form->get('submit')); ?>
                </div>
            </div>

        </fieldset>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>
<script>
    $(document).ready(function () {
        $('[data-toggle="popover"]').popover();
    });
</script>