<?php

use Zend\Form\Element;
use Zend\Form\Element\Captcha;
use Zend\Captcha\Image as CaptchaImage;

$form = $this->form;

$csrf = new Element\Csrf('security');
$form->add(array(
    'type' => 'Zend\Form\Element\Csrf',
    'name' => 'security',
    'options' => array(
        'csrf_options' => array(
            'timeout' => 600
        )
    )
        )
);

$form->setAttributes(array(
    'class' => 'form-horizontal'
        )
);
$form->setAttribute('action', $this->url(
                'login/process', array(
            'action' => 'authenticate',
                )
        )
);


$captchaImage = new CaptchaImage(array(
    'font' => getcwd() . '\data\captcha\fonts\arial.TTF',
    'width' => 250,
    'height' => 100,
    'dotNoiseLevel' => 40,
    'lineNoiseLevel' => 3)
);
$captchaImage->setImgDir(getcwd() . '/public/img/captcha');
$captchaImage->setImgUrl('/img/captcha');

//add captcha element...
$form->add(array(
    'type' => 'Zend\Form\Element\Captcha',
    'name' => 'captcha',
    'attributes' => array(
        'id' => 'captcha',
        'class' => 'form-control',
        'placeholder' => 'Please enter the above characters',
        'required' => TRUE,
    ),
    'options' => array(
        'captcha' => $captchaImage,
    ),
));

$form->prepare();

echo '<div class="col-lg-10"><div class="well bs-component">';

echo $this->form()->openTag($form);

echo '<fieldset><legend>Login</legend>';

echo '<div class="form-group"><label class="col-lg-2 control-label" for="username">Username:</label><div class="col-lg-10">';
echo $this->formRow($form->get('username'));
echo '</div></div>';

echo '<div class="form-group"><label class="col-lg-2 control-label" for="password">Password:</label><div class="col-lg-10">';
echo $this->formRow($form->get('password'));
echo '</div></div>';

echo '<div class="form-group"><label class="col-lg-2 control-label" for="rememberme">Remember device?</label><div class="col-lg-10">';
echo $this->formRow($form->get('rememberme'));
echo '</div></div>';

echo '<div class="form-group"><label class="col-lg-2 control-label" for="captcha">Are you human?</label><div class="col-lg-10">';
echo $this->formRow($form->get('captcha'));
echo '</div></div>';

echo $this->formRow($form->get('security'));

echo '<div class="form-group"><div class="col-sm-offset-2 col-sm-10">';
echo $this->formSubmit($form->get('submit'));
echo '</div></div>';

echo '</fieldset>';

echo $this->form()->closeTag();

echo '</div></div>';
