<?php 

use Zend\Captcha;
use Zend\Form\Element;
use Zend\Form\Fieldset;
use Zend\Form\Form;
use Zend\InputFilter\Input;
use Zend\InputFilter\InputFilter;

$form = $this->form;

$form->setAttributes(array(
    'class'  => 'form-horizontal'
));
$form->setAttribute('action', $this->url(
    'login/process',
    array(
        'action'     => 'authenticate',
    )
));
$form->prepare();
 
echo '<div class="well bs-component">';

echo $this->form()->openTag($form);

echo '<fieldset><legend>Login</legend>';

echo    '<div class="form-group"><label class="col-lg-2 control-label" for="firstname">Firstname:</label><div class="col-lg-10">';
echo    $this->formRow($form->get('firstname'));
echo    '</div></div>';

echo    '<div class="form-group"><label class="col-lg-2 control-label" for="lastname">Lastname:</label><div class="col-lg-10">';
echo    $this->formRow($form->get('lastname'));
echo    '</div></div>';

echo    '<div class="form-group"><label class="col-lg-2 control-label" for="username">Username:</label><div class="col-lg-10">';
echo    $this->formRow($form->get('username'));
echo    '</div></div>';

echo    '<div class="form-group"><label class="col-lg-2 control-label" for="password">Password:</label><div class="col-lg-10">';
echo    $this->formRow($form->get('password'));
echo    '</div></div>';

echo    '<div class="form-group"><div class="col-sm-offset-2 col-sm-10">';
echo    $this->formSubmit($form->get('submit'));
echo    '</div></div>';

echo '</fieldset>';


echo $this->form()->closeTag();

echo '</div>';


if (isset($this->messages)){

    echo '<div class="bs-component">';
    
    if($this->messages->setNamespace('warning')->hasMessages())
    {
        echo '<div class="panel panel-warning"><div class="panel-heading">';
        echo '<h3 class="panel-title">Notice</h3>';
        echo '</div>';
    }
    else if($this->messages->setNamespace('error')->hasMessages())
    {
        echo '<div class="panel panel-danger"><div class="panel-heading">';
        echo '<h3 class="panel-title">Error</h3>';
        echo '</div>';
    }
    else{
        echo '<div class="panel panel-info"><div class="panel-heading">';
        echo '<h3 class="panel-title">Info</h3>';
        echo '</div>';
    }
    
    echo '<div class="panel-body">';
    
    foreach($this->messages as $message)
    {
        echo '<p>'.$message.'</p>';
    }
                
    echo '</div></div></div></div>';
}

