<?php
echo $this->UIPageTitleFormatter($this->navigation('navigation')->findActive('navigation')['page']->label);

$form = $this->form;
$form->setAttribute('action', $this->url('business-admin/labour-items', array('action' => 'edit', 'id' => $this->id,)));
$form->setAttributes(array('class' => 'form-horizontal'));
$form->prepare();
?>

<div class="well bs-component">

    <?php echo $this->form()->openTag($form); ?>

    <fieldset>
        <legend>Edit Labour Item</legend>

        <?php echo $this->formHidden($form->get('LabourID')); ?>

        <div class="form-group">
            <label class="col-md-2 control-label" for="LabourName">Item Name:</label>
            <div class="col-md-10">
                <?php echo $this->formRow($form->get('LabourName')); ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label" for="LabourUnitCost">Unit Cost:</label>
            <div class="col-md-10">
                <div class="input-group">
                    <div class="input-group-addon">£</div>
                    <?php echo $this->formRow($form->get('LabourUnitCost')); ?>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label" for="LabourCode">Code:</label>
            <div class="col-md-10">
                <?php echo $this->formRow($form->get('LabourCode')); ?>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-3 col-md-offset-9">
                <a href="/business-admin/labour-items" type="reset" class="btn btn-warning btn-default margin-right-10">Cancel</a>
                <?php echo $this->formSubmit($form->get('submit')); ?>
            </div>
        </div>

    </fieldset>

    <?php echo $this->form()->closeTag(); ?>

</div>
