<?php

echo $this->UIPageTitleFormatter($this->navigation('navigation')->findActive('navigation')['page']->label);

$form = $this->form;
$form->setAttribute('action', $this->url('business-admin/labour-items', array('action' => 'edit', 'id' => $this->id,)));
$form->setAttributes(array('class' => 'form-horizontal'));
$form->prepare();

echo '<div class="well bs-component">';

echo $this->form()->openTag($form);

echo '<fieldset><legend>Edit Labour Item</legend>';

echo $this->formHidden($form->get('LabourID'));

echo '<div class="form-group">';
echo '<label class="col-lg-2 control-label" for="LabourName">Labour Item Name:</label><div class="col-lg-10">';
echo $this->formRow($form->get('LabourName'));
echo '</div></div>';

echo '<div class="form-group">';
echo '<label class="col-lg-2 control-label" for="LabourUnitCost">Labour Item Unit Cost:</label><div class="col-lg-10">';
echo $this->formRow($form->get('LabourUnitCost'));
echo '</div></div>';

echo '<div class="form-group">';
echo '<label class="col-lg-2 control-label" for="LabourCode">Labour Item Code:</label><div class="col-lg-10">';
echo $this->formRow($form->get('LabourCode'));
echo '</div></div>';


echo '<div class="form-group">';
echo '<div class="col-lg-10 col-lg-offset-2">';
echo '<a href="/business-admin/labour-items" type="reset" class="btn btn-default btn-sm">Cancel</a>';
$form->get('submit')->setAttribute('class', 'btn btn-warning btn-sm');
echo $this->formSubmit($form->get('submit'));
echo '</div></div>';

echo '</fieldset>';

echo $this->form()->closeTag();

echo '</div>';
