<?php
echo $this->UIPageTitleFormatter($this->navigation('navigation')->findActive('navigation')['page']->label);
echo $this->UIAccessControlButtons($_SESSION['AnnieHaak']['storage']['userInfo']['roleLevel'], 'add', '/business-admin/labour-items/add', 'Add new Labour Item');
?>

<table class="table table-striped table-hover">
    <thead>
        <tr class="text-info">
            <th>Labour Items</th>
            <th>Unit Cost</th>
            <th>Code</th>
            <th colspan="2" style="width: 25%;">Actions</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($labourItems as $labourItem) : ?>
            <tr>
                <td>
                    <?php echo $this->escapeHtml($labourItem->LabourName); ?>
                </td>
                <td>
                    <?php echo $this->UICurrencyFormatter($labourItem->LabourUnitCost, true); ?>
                </td>
                <td>
                    <?php echo $labourItem->LabourCode; ?>
                </td>
                <td>
                    <?php echo $this->UIAccessControlButtons($_SESSION['AnnieHaak']['storage']['userInfo']['roleLevel'], 'edit', '/business-admin/labour-items/edit/' . $labourItem->LabourID, 'Edit'); ?>
                </td>
                <td>
                    <?php echo $this->UIAccessControlButtons($_SESSION['AnnieHaak']['storage']['userInfo']['roleLevel'], 'delete', '/business-admin/labour-items/delete/' . $labourItem->LabourID, 'Delete'); ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>